# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['CableArgs', 'Cable']

@pulumi.input_type
class CableArgs:
    def __init__(__self__, *,
                 a_terminations: pulumi.Input[Sequence[pulumi.Input['CableATerminationArgs']]],
                 b_terminations: pulumi.Input[Sequence[pulumi.Input['CableBTerminationArgs']]],
                 status: pulumi.Input[_builtins.str],
                 cable_id: Optional[pulumi.Input[_builtins.str]] = None,
                 color_hex: Optional[pulumi.Input[_builtins.str]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 label: Optional[pulumi.Input[_builtins.str]] = None,
                 length: Optional[pulumi.Input[_builtins.float]] = None,
                 length_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Cable resource.
        :param pulumi.Input[_builtins.str] status: One of [connected, planned, decommissioning].
        :param pulumi.Input[_builtins.str] length_unit: One of [km, m, cm, mi, ft, in]. Required when <span pulumi-lang-nodejs="`length`" pulumi-lang-dotnet="`Length`" pulumi-lang-go="`length`" pulumi-lang-python="`length`" pulumi-lang-yaml="`length`" pulumi-lang-java="`length`">`length`</span> is set.
        :param pulumi.Input[_builtins.str] type: One of [cat3, cat5, cat5e, cat6, cat6a, cat7, cat7a, cat8, dac-active, dac-passive, mrj21-trunk, coaxial, mmf, mmf-om1, mmf-om2, mmf-om3, mmf-om4, mmf-om5, smf, smf-os1, smf-os2, aoc, power].
        """
        pulumi.set(__self__, "a_terminations", a_terminations)
        pulumi.set(__self__, "b_terminations", b_terminations)
        pulumi.set(__self__, "status", status)
        if cable_id is not None:
            pulumi.set(__self__, "cable_id", cable_id)
        if color_hex is not None:
            pulumi.set(__self__, "color_hex", color_hex)
        if comments is not None:
            pulumi.set(__self__, "comments", comments)
        if custom_fields is not None:
            pulumi.set(__self__, "custom_fields", custom_fields)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if label is not None:
            pulumi.set(__self__, "label", label)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if length_unit is not None:
            pulumi.set(__self__, "length_unit", length_unit)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="aTerminations")
    def a_terminations(self) -> pulumi.Input[Sequence[pulumi.Input['CableATerminationArgs']]]:
        return pulumi.get(self, "a_terminations")

    @a_terminations.setter
    def a_terminations(self, value: pulumi.Input[Sequence[pulumi.Input['CableATerminationArgs']]]):
        pulumi.set(self, "a_terminations", value)

    @_builtins.property
    @pulumi.getter(name="bTerminations")
    def b_terminations(self) -> pulumi.Input[Sequence[pulumi.Input['CableBTerminationArgs']]]:
        return pulumi.get(self, "b_terminations")

    @b_terminations.setter
    def b_terminations(self, value: pulumi.Input[Sequence[pulumi.Input['CableBTerminationArgs']]]):
        pulumi.set(self, "b_terminations", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[_builtins.str]:
        """
        One of [connected, planned, decommissioning].
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="cableId")
    def cable_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cable_id")

    @cable_id.setter
    def cable_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cable_id", value)

    @_builtins.property
    @pulumi.getter(name="colorHex")
    def color_hex(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "color_hex")

    @color_hex.setter
    def color_hex(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "color_hex", value)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "comments")

    @comments.setter
    def comments(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "comments", value)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "custom_fields")

    @custom_fields.setter
    def custom_fields(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_fields", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "length")

    @length.setter
    def length(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "length", value)

    @_builtins.property
    @pulumi.getter(name="lengthUnit")
    def length_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        One of [km, m, cm, mi, ft, in]. Required when <span pulumi-lang-nodejs="`length`" pulumi-lang-dotnet="`Length`" pulumi-lang-go="`length`" pulumi-lang-python="`length`" pulumi-lang-yaml="`length`" pulumi-lang-java="`length`">`length`</span> is set.
        """
        return pulumi.get(self, "length_unit")

    @length_unit.setter
    def length_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "length_unit", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        One of [cat3, cat5, cat5e, cat6, cat6a, cat7, cat7a, cat8, dac-active, dac-passive, mrj21-trunk, coaxial, mmf, mmf-om1, mmf-om2, mmf-om3, mmf-om4, mmf-om5, smf, smf-os1, smf-os2, aoc, power].
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.input_type
class _CableState:
    def __init__(__self__, *,
                 a_terminations: Optional[pulumi.Input[Sequence[pulumi.Input['CableATerminationArgs']]]] = None,
                 b_terminations: Optional[pulumi.Input[Sequence[pulumi.Input['CableBTerminationArgs']]]] = None,
                 cable_id: Optional[pulumi.Input[_builtins.str]] = None,
                 color_hex: Optional[pulumi.Input[_builtins.str]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 label: Optional[pulumi.Input[_builtins.str]] = None,
                 length: Optional[pulumi.Input[_builtins.float]] = None,
                 length_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Cable resources.
        :param pulumi.Input[_builtins.str] length_unit: One of [km, m, cm, mi, ft, in]. Required when <span pulumi-lang-nodejs="`length`" pulumi-lang-dotnet="`Length`" pulumi-lang-go="`length`" pulumi-lang-python="`length`" pulumi-lang-yaml="`length`" pulumi-lang-java="`length`">`length`</span> is set.
        :param pulumi.Input[_builtins.str] status: One of [connected, planned, decommissioning].
        :param pulumi.Input[_builtins.str] type: One of [cat3, cat5, cat5e, cat6, cat6a, cat7, cat7a, cat8, dac-active, dac-passive, mrj21-trunk, coaxial, mmf, mmf-om1, mmf-om2, mmf-om3, mmf-om4, mmf-om5, smf, smf-os1, smf-os2, aoc, power].
        """
        if a_terminations is not None:
            pulumi.set(__self__, "a_terminations", a_terminations)
        if b_terminations is not None:
            pulumi.set(__self__, "b_terminations", b_terminations)
        if cable_id is not None:
            pulumi.set(__self__, "cable_id", cable_id)
        if color_hex is not None:
            pulumi.set(__self__, "color_hex", color_hex)
        if comments is not None:
            pulumi.set(__self__, "comments", comments)
        if custom_fields is not None:
            pulumi.set(__self__, "custom_fields", custom_fields)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if label is not None:
            pulumi.set(__self__, "label", label)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if length_unit is not None:
            pulumi.set(__self__, "length_unit", length_unit)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tags_alls is not None:
            pulumi.set(__self__, "tags_alls", tags_alls)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="aTerminations")
    def a_terminations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['CableATerminationArgs']]]]:
        return pulumi.get(self, "a_terminations")

    @a_terminations.setter
    def a_terminations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['CableATerminationArgs']]]]):
        pulumi.set(self, "a_terminations", value)

    @_builtins.property
    @pulumi.getter(name="bTerminations")
    def b_terminations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['CableBTerminationArgs']]]]:
        return pulumi.get(self, "b_terminations")

    @b_terminations.setter
    def b_terminations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['CableBTerminationArgs']]]]):
        pulumi.set(self, "b_terminations", value)

    @_builtins.property
    @pulumi.getter(name="cableId")
    def cable_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cable_id")

    @cable_id.setter
    def cable_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cable_id", value)

    @_builtins.property
    @pulumi.getter(name="colorHex")
    def color_hex(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "color_hex")

    @color_hex.setter
    def color_hex(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "color_hex", value)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "comments")

    @comments.setter
    def comments(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "comments", value)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "custom_fields")

    @custom_fields.setter
    def custom_fields(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_fields", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "length")

    @length.setter
    def length(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "length", value)

    @_builtins.property
    @pulumi.getter(name="lengthUnit")
    def length_unit(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        One of [km, m, cm, mi, ft, in]. Required when <span pulumi-lang-nodejs="`length`" pulumi-lang-dotnet="`Length`" pulumi-lang-go="`length`" pulumi-lang-python="`length`" pulumi-lang-yaml="`length`" pulumi-lang-java="`length`">`length`</span> is set.
        """
        return pulumi.get(self, "length_unit")

    @length_unit.setter
    def length_unit(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "length_unit", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        One of [connected, planned, decommissioning].
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags_alls")

    @tags_alls.setter
    def tags_alls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags_alls", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        One of [cat3, cat5, cat5e, cat6, cat6a, cat7, cat7a, cat8, dac-active, dac-passive, mrj21-trunk, coaxial, mmf, mmf-om1, mmf-om2, mmf-om3, mmf-om4, mmf-om5, smf, smf-os1, smf-os2, aoc, power].
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.type_token("netbox:index/cable:Cable")
class Cable(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 a_terminations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CableATerminationArgs', 'CableATerminationArgsDict']]]]] = None,
                 b_terminations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CableBTerminationArgs', 'CableBTerminationArgsDict']]]]] = None,
                 cable_id: Optional[pulumi.Input[_builtins.str]] = None,
                 color_hex: Optional[pulumi.Input[_builtins.str]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 label: Optional[pulumi.Input[_builtins.str]] = None,
                 length: Optional[pulumi.Input[_builtins.float]] = None,
                 length_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Cable resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] length_unit: One of [km, m, cm, mi, ft, in]. Required when <span pulumi-lang-nodejs="`length`" pulumi-lang-dotnet="`Length`" pulumi-lang-go="`length`" pulumi-lang-python="`length`" pulumi-lang-yaml="`length`" pulumi-lang-java="`length`">`length`</span> is set.
        :param pulumi.Input[_builtins.str] status: One of [connected, planned, decommissioning].
        :param pulumi.Input[_builtins.str] type: One of [cat3, cat5, cat5e, cat6, cat6a, cat7, cat7a, cat8, dac-active, dac-passive, mrj21-trunk, coaxial, mmf, mmf-om1, mmf-om2, mmf-om3, mmf-om4, mmf-om5, smf, smf-os1, smf-os2, aoc, power].
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CableArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Cable resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param CableArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CableArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 a_terminations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CableATerminationArgs', 'CableATerminationArgsDict']]]]] = None,
                 b_terminations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CableBTerminationArgs', 'CableBTerminationArgsDict']]]]] = None,
                 cable_id: Optional[pulumi.Input[_builtins.str]] = None,
                 color_hex: Optional[pulumi.Input[_builtins.str]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 label: Optional[pulumi.Input[_builtins.str]] = None,
                 length: Optional[pulumi.Input[_builtins.float]] = None,
                 length_unit: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CableArgs.__new__(CableArgs)

            if a_terminations is None and not opts.urn:
                raise TypeError("Missing required property 'a_terminations'")
            __props__.__dict__["a_terminations"] = a_terminations
            if b_terminations is None and not opts.urn:
                raise TypeError("Missing required property 'b_terminations'")
            __props__.__dict__["b_terminations"] = b_terminations
            __props__.__dict__["cable_id"] = cable_id
            __props__.__dict__["color_hex"] = color_hex
            __props__.__dict__["comments"] = comments
            __props__.__dict__["custom_fields"] = custom_fields
            __props__.__dict__["description"] = description
            __props__.__dict__["label"] = label
            __props__.__dict__["length"] = length
            __props__.__dict__["length_unit"] = length_unit
            if status is None and not opts.urn:
                raise TypeError("Missing required property 'status'")
            __props__.__dict__["status"] = status
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_id"] = tenant_id
            __props__.__dict__["type"] = type
            __props__.__dict__["tags_alls"] = None
        super(Cable, __self__).__init__(
            'netbox:index/cable:Cable',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            a_terminations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CableATerminationArgs', 'CableATerminationArgsDict']]]]] = None,
            b_terminations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CableBTerminationArgs', 'CableBTerminationArgsDict']]]]] = None,
            cable_id: Optional[pulumi.Input[_builtins.str]] = None,
            color_hex: Optional[pulumi.Input[_builtins.str]] = None,
            comments: Optional[pulumi.Input[_builtins.str]] = None,
            custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            label: Optional[pulumi.Input[_builtins.str]] = None,
            length: Optional[pulumi.Input[_builtins.float]] = None,
            length_unit: Optional[pulumi.Input[_builtins.str]] = None,
            status: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
            type: Optional[pulumi.Input[_builtins.str]] = None) -> 'Cable':
        """
        Get an existing Cable resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] length_unit: One of [km, m, cm, mi, ft, in]. Required when <span pulumi-lang-nodejs="`length`" pulumi-lang-dotnet="`Length`" pulumi-lang-go="`length`" pulumi-lang-python="`length`" pulumi-lang-yaml="`length`" pulumi-lang-java="`length`">`length`</span> is set.
        :param pulumi.Input[_builtins.str] status: One of [connected, planned, decommissioning].
        :param pulumi.Input[_builtins.str] type: One of [cat3, cat5, cat5e, cat6, cat6a, cat7, cat7a, cat8, dac-active, dac-passive, mrj21-trunk, coaxial, mmf, mmf-om1, mmf-om2, mmf-om3, mmf-om4, mmf-om5, smf, smf-os1, smf-os2, aoc, power].
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CableState.__new__(_CableState)

        __props__.__dict__["a_terminations"] = a_terminations
        __props__.__dict__["b_terminations"] = b_terminations
        __props__.__dict__["cable_id"] = cable_id
        __props__.__dict__["color_hex"] = color_hex
        __props__.__dict__["comments"] = comments
        __props__.__dict__["custom_fields"] = custom_fields
        __props__.__dict__["description"] = description
        __props__.__dict__["label"] = label
        __props__.__dict__["length"] = length
        __props__.__dict__["length_unit"] = length_unit
        __props__.__dict__["status"] = status
        __props__.__dict__["tags"] = tags
        __props__.__dict__["tags_alls"] = tags_alls
        __props__.__dict__["tenant_id"] = tenant_id
        __props__.__dict__["type"] = type
        return Cable(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="aTerminations")
    def a_terminations(self) -> pulumi.Output[Sequence['outputs.CableATermination']]:
        return pulumi.get(self, "a_terminations")

    @_builtins.property
    @pulumi.getter(name="bTerminations")
    def b_terminations(self) -> pulumi.Output[Sequence['outputs.CableBTermination']]:
        return pulumi.get(self, "b_terminations")

    @_builtins.property
    @pulumi.getter(name="cableId")
    def cable_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "cable_id")

    @_builtins.property
    @pulumi.getter(name="colorHex")
    def color_hex(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "color_hex")

    @_builtins.property
    @pulumi.getter
    def comments(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "comments")

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "custom_fields")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "label")

    @_builtins.property
    @pulumi.getter
    def length(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "length")

    @_builtins.property
    @pulumi.getter(name="lengthUnit")
    def length_unit(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        One of [km, m, cm, mi, ft, in]. Required when <span pulumi-lang-nodejs="`length`" pulumi-lang-dotnet="`Length`" pulumi-lang-go="`length`" pulumi-lang-python="`length`" pulumi-lang-yaml="`length`" pulumi-lang-java="`length`">`length`</span> is set.
        """
        return pulumi.get(self, "length_unit")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        One of [connected, planned, decommissioning].
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "tags_alls")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        One of [cat3, cat5, cat5e, cat6, cat6a, cat7, cat7a, cat8, dac-active, dac-passive, mrj21-trunk, coaxial, mmf, mmf-om1, mmf-om2, mmf-om3, mmf-om4, mmf-om5, smf, smf-os1, smf-os2, aoc, power].
        """
        return pulumi.get(self, "type")

