# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DeviceArgs', 'Device']

@pulumi.input_type
class DeviceArgs:
    def __init__(__self__, *,
                 device_type_id: pulumi.Input[_builtins.float],
                 role_id: pulumi.Input[_builtins.float],
                 site_id: pulumi.Input[_builtins.float],
                 asset_tag: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_id: Optional[pulumi.Input[_builtins.float]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 config_template_id: Optional[pulumi.Input[_builtins.float]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 device_id: Optional[pulumi.Input[_builtins.str]] = None,
                 local_context_data: Optional[pulumi.Input[_builtins.str]] = None,
                 location_id: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 platform_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_face: Optional[pulumi.Input[_builtins.str]] = None,
                 rack_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_position: Optional[pulumi.Input[_builtins.float]] = None,
                 serial: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_id: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_master: Optional[pulumi.Input[_builtins.bool]] = None,
                 virtual_chassis_position: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_priority: Optional[pulumi.Input[_builtins.float]] = None):
        """
        The set of arguments for constructing a Device resource.
        :param pulumi.Input[_builtins.str] local_context_data: This is best managed through the use of <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> and a map of settings.
        :param pulumi.Input[_builtins.str] rack_face: Valid values are <span pulumi-lang-nodejs="`front`" pulumi-lang-dotnet="`Front`" pulumi-lang-go="`front`" pulumi-lang-python="`front`" pulumi-lang-yaml="`front`" pulumi-lang-java="`front`">`front`</span> and <span pulumi-lang-nodejs="`rear`" pulumi-lang-dotnet="`Rear`" pulumi-lang-go="`rear`" pulumi-lang-python="`rear`" pulumi-lang-yaml="`rear`" pulumi-lang-java="`rear`">`rear`</span>. Required when <span pulumi-lang-nodejs="`rackPosition`" pulumi-lang-dotnet="`RackPosition`" pulumi-lang-go="`rackPosition`" pulumi-lang-python="`rack_position`" pulumi-lang-yaml="`rackPosition`" pulumi-lang-java="`rackPosition`">`rack_position`</span> is set.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`offline`" pulumi-lang-dotnet="`Offline`" pulumi-lang-go="`offline`" pulumi-lang-python="`offline`" pulumi-lang-yaml="`offline`" pulumi-lang-java="`offline`">`offline`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staged`" pulumi-lang-dotnet="`Staged`" pulumi-lang-go="`staged`" pulumi-lang-python="`staged`" pulumi-lang-yaml="`staged`" pulumi-lang-java="`staged`">`staged`</span>, <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`">`failed`</span>, <span pulumi-lang-nodejs="`inventory`" pulumi-lang-dotnet="`Inventory`" pulumi-lang-go="`inventory`" pulumi-lang-python="`inventory`" pulumi-lang-yaml="`inventory`" pulumi-lang-java="`inventory`">`inventory`</span> and <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        :param pulumi.Input[_builtins.float] virtual_chassis_id: Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        :param pulumi.Input[_builtins.bool] virtual_chassis_master: Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        pulumi.set(__self__, "device_type_id", device_type_id)
        pulumi.set(__self__, "role_id", role_id)
        pulumi.set(__self__, "site_id", site_id)
        if asset_tag is not None:
            pulumi.set(__self__, "asset_tag", asset_tag)
        if cluster_id is not None:
            pulumi.set(__self__, "cluster_id", cluster_id)
        if comments is not None:
            pulumi.set(__self__, "comments", comments)
        if config_template_id is not None:
            pulumi.set(__self__, "config_template_id", config_template_id)
        if custom_fields is not None:
            pulumi.set(__self__, "custom_fields", custom_fields)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if device_id is not None:
            pulumi.set(__self__, "device_id", device_id)
        if local_context_data is not None:
            pulumi.set(__self__, "local_context_data", local_context_data)
        if location_id is not None:
            pulumi.set(__self__, "location_id", location_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if platform_id is not None:
            pulumi.set(__self__, "platform_id", platform_id)
        if rack_face is not None:
            pulumi.set(__self__, "rack_face", rack_face)
        if rack_id is not None:
            pulumi.set(__self__, "rack_id", rack_id)
        if rack_position is not None:
            pulumi.set(__self__, "rack_position", rack_position)
        if serial is not None:
            pulumi.set(__self__, "serial", serial)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if virtual_chassis_id is not None:
            pulumi.set(__self__, "virtual_chassis_id", virtual_chassis_id)
        if virtual_chassis_master is not None:
            pulumi.set(__self__, "virtual_chassis_master", virtual_chassis_master)
        if virtual_chassis_position is not None:
            pulumi.set(__self__, "virtual_chassis_position", virtual_chassis_position)
        if virtual_chassis_priority is not None:
            pulumi.set(__self__, "virtual_chassis_priority", virtual_chassis_priority)

    @_builtins.property
    @pulumi.getter(name="deviceTypeId")
    def device_type_id(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "device_type_id")

    @device_type_id.setter
    def device_type_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "device_type_id", value)

    @_builtins.property
    @pulumi.getter(name="roleId")
    def role_id(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "role_id")

    @role_id.setter
    def role_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "role_id", value)

    @_builtins.property
    @pulumi.getter(name="siteId")
    def site_id(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "site_id")

    @site_id.setter
    def site_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "site_id", value)

    @_builtins.property
    @pulumi.getter(name="assetTag")
    def asset_tag(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "asset_tag")

    @asset_tag.setter
    def asset_tag(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "asset_tag", value)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "cluster_id", value)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "comments")

    @comments.setter
    def comments(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "comments", value)

    @_builtins.property
    @pulumi.getter(name="configTemplateId")
    def config_template_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "config_template_id")

    @config_template_id.setter
    def config_template_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "config_template_id", value)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "custom_fields")

    @custom_fields.setter
    def custom_fields(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_fields", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="deviceId")
    def device_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "device_id")

    @device_id.setter
    def device_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "device_id", value)

    @_builtins.property
    @pulumi.getter(name="localContextData")
    def local_context_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        This is best managed through the use of <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> and a map of settings.
        """
        return pulumi.get(self, "local_context_data")

    @local_context_data.setter
    def local_context_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "local_context_data", value)

    @_builtins.property
    @pulumi.getter(name="locationId")
    def location_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "location_id")

    @location_id.setter
    def location_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "location_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="platformId")
    def platform_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "platform_id")

    @platform_id.setter
    def platform_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "platform_id", value)

    @_builtins.property
    @pulumi.getter(name="rackFace")
    def rack_face(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`front`" pulumi-lang-dotnet="`Front`" pulumi-lang-go="`front`" pulumi-lang-python="`front`" pulumi-lang-yaml="`front`" pulumi-lang-java="`front`">`front`</span> and <span pulumi-lang-nodejs="`rear`" pulumi-lang-dotnet="`Rear`" pulumi-lang-go="`rear`" pulumi-lang-python="`rear`" pulumi-lang-yaml="`rear`" pulumi-lang-java="`rear`">`rear`</span>. Required when <span pulumi-lang-nodejs="`rackPosition`" pulumi-lang-dotnet="`RackPosition`" pulumi-lang-go="`rackPosition`" pulumi-lang-python="`rack_position`" pulumi-lang-yaml="`rackPosition`" pulumi-lang-java="`rackPosition`">`rack_position`</span> is set.
        """
        return pulumi.get(self, "rack_face")

    @rack_face.setter
    def rack_face(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rack_face", value)

    @_builtins.property
    @pulumi.getter(name="rackId")
    def rack_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "rack_id")

    @rack_id.setter
    def rack_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "rack_id", value)

    @_builtins.property
    @pulumi.getter(name="rackPosition")
    def rack_position(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "rack_position")

    @rack_position.setter
    def rack_position(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "rack_position", value)

    @_builtins.property
    @pulumi.getter
    def serial(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "serial")

    @serial.setter
    def serial(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "serial", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`offline`" pulumi-lang-dotnet="`Offline`" pulumi-lang-go="`offline`" pulumi-lang-python="`offline`" pulumi-lang-yaml="`offline`" pulumi-lang-java="`offline`">`offline`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staged`" pulumi-lang-dotnet="`Staged`" pulumi-lang-go="`staged`" pulumi-lang-python="`staged`" pulumi-lang-yaml="`staged`" pulumi-lang-java="`staged`">`staged`</span>, <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`">`failed`</span>, <span pulumi-lang-nodejs="`inventory`" pulumi-lang-dotnet="`Inventory`" pulumi-lang-go="`inventory`" pulumi-lang-python="`inventory`" pulumi-lang-yaml="`inventory`" pulumi-lang-java="`inventory`">`inventory`</span> and <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter(name="virtualChassisId")
    def virtual_chassis_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        return pulumi.get(self, "virtual_chassis_id")

    @virtual_chassis_id.setter
    def virtual_chassis_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "virtual_chassis_id", value)

    @_builtins.property
    @pulumi.getter(name="virtualChassisMaster")
    def virtual_chassis_master(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        return pulumi.get(self, "virtual_chassis_master")

    @virtual_chassis_master.setter
    def virtual_chassis_master(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "virtual_chassis_master", value)

    @_builtins.property
    @pulumi.getter(name="virtualChassisPosition")
    def virtual_chassis_position(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "virtual_chassis_position")

    @virtual_chassis_position.setter
    def virtual_chassis_position(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "virtual_chassis_position", value)

    @_builtins.property
    @pulumi.getter(name="virtualChassisPriority")
    def virtual_chassis_priority(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "virtual_chassis_priority")

    @virtual_chassis_priority.setter
    def virtual_chassis_priority(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "virtual_chassis_priority", value)


@pulumi.input_type
class _DeviceState:
    def __init__(__self__, *,
                 asset_tag: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_id: Optional[pulumi.Input[_builtins.float]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 config_template_id: Optional[pulumi.Input[_builtins.float]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 device_id: Optional[pulumi.Input[_builtins.str]] = None,
                 device_type_id: Optional[pulumi.Input[_builtins.float]] = None,
                 local_context_data: Optional[pulumi.Input[_builtins.str]] = None,
                 location_id: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 platform_id: Optional[pulumi.Input[_builtins.float]] = None,
                 primary_ipv4: Optional[pulumi.Input[_builtins.float]] = None,
                 primary_ipv6: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_face: Optional[pulumi.Input[_builtins.str]] = None,
                 rack_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_position: Optional[pulumi.Input[_builtins.float]] = None,
                 role_id: Optional[pulumi.Input[_builtins.float]] = None,
                 serial: Optional[pulumi.Input[_builtins.str]] = None,
                 site_id: Optional[pulumi.Input[_builtins.float]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_id: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_master: Optional[pulumi.Input[_builtins.bool]] = None,
                 virtual_chassis_position: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_priority: Optional[pulumi.Input[_builtins.float]] = None):
        """
        Input properties used for looking up and filtering Device resources.
        :param pulumi.Input[_builtins.str] local_context_data: This is best managed through the use of <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> and a map of settings.
        :param pulumi.Input[_builtins.str] rack_face: Valid values are <span pulumi-lang-nodejs="`front`" pulumi-lang-dotnet="`Front`" pulumi-lang-go="`front`" pulumi-lang-python="`front`" pulumi-lang-yaml="`front`" pulumi-lang-java="`front`">`front`</span> and <span pulumi-lang-nodejs="`rear`" pulumi-lang-dotnet="`Rear`" pulumi-lang-go="`rear`" pulumi-lang-python="`rear`" pulumi-lang-yaml="`rear`" pulumi-lang-java="`rear`">`rear`</span>. Required when <span pulumi-lang-nodejs="`rackPosition`" pulumi-lang-dotnet="`RackPosition`" pulumi-lang-go="`rackPosition`" pulumi-lang-python="`rack_position`" pulumi-lang-yaml="`rackPosition`" pulumi-lang-java="`rackPosition`">`rack_position`</span> is set.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`offline`" pulumi-lang-dotnet="`Offline`" pulumi-lang-go="`offline`" pulumi-lang-python="`offline`" pulumi-lang-yaml="`offline`" pulumi-lang-java="`offline`">`offline`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staged`" pulumi-lang-dotnet="`Staged`" pulumi-lang-go="`staged`" pulumi-lang-python="`staged`" pulumi-lang-yaml="`staged`" pulumi-lang-java="`staged`">`staged`</span>, <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`">`failed`</span>, <span pulumi-lang-nodejs="`inventory`" pulumi-lang-dotnet="`Inventory`" pulumi-lang-go="`inventory`" pulumi-lang-python="`inventory`" pulumi-lang-yaml="`inventory`" pulumi-lang-java="`inventory`">`inventory`</span> and <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        :param pulumi.Input[_builtins.float] virtual_chassis_id: Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        :param pulumi.Input[_builtins.bool] virtual_chassis_master: Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        if asset_tag is not None:
            pulumi.set(__self__, "asset_tag", asset_tag)
        if cluster_id is not None:
            pulumi.set(__self__, "cluster_id", cluster_id)
        if comments is not None:
            pulumi.set(__self__, "comments", comments)
        if config_template_id is not None:
            pulumi.set(__self__, "config_template_id", config_template_id)
        if custom_fields is not None:
            pulumi.set(__self__, "custom_fields", custom_fields)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if device_id is not None:
            pulumi.set(__self__, "device_id", device_id)
        if device_type_id is not None:
            pulumi.set(__self__, "device_type_id", device_type_id)
        if local_context_data is not None:
            pulumi.set(__self__, "local_context_data", local_context_data)
        if location_id is not None:
            pulumi.set(__self__, "location_id", location_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if platform_id is not None:
            pulumi.set(__self__, "platform_id", platform_id)
        if primary_ipv4 is not None:
            pulumi.set(__self__, "primary_ipv4", primary_ipv4)
        if primary_ipv6 is not None:
            pulumi.set(__self__, "primary_ipv6", primary_ipv6)
        if rack_face is not None:
            pulumi.set(__self__, "rack_face", rack_face)
        if rack_id is not None:
            pulumi.set(__self__, "rack_id", rack_id)
        if rack_position is not None:
            pulumi.set(__self__, "rack_position", rack_position)
        if role_id is not None:
            pulumi.set(__self__, "role_id", role_id)
        if serial is not None:
            pulumi.set(__self__, "serial", serial)
        if site_id is not None:
            pulumi.set(__self__, "site_id", site_id)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tags_alls is not None:
            pulumi.set(__self__, "tags_alls", tags_alls)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if virtual_chassis_id is not None:
            pulumi.set(__self__, "virtual_chassis_id", virtual_chassis_id)
        if virtual_chassis_master is not None:
            pulumi.set(__self__, "virtual_chassis_master", virtual_chassis_master)
        if virtual_chassis_position is not None:
            pulumi.set(__self__, "virtual_chassis_position", virtual_chassis_position)
        if virtual_chassis_priority is not None:
            pulumi.set(__self__, "virtual_chassis_priority", virtual_chassis_priority)

    @_builtins.property
    @pulumi.getter(name="assetTag")
    def asset_tag(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "asset_tag")

    @asset_tag.setter
    def asset_tag(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "asset_tag", value)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "cluster_id", value)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "comments")

    @comments.setter
    def comments(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "comments", value)

    @_builtins.property
    @pulumi.getter(name="configTemplateId")
    def config_template_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "config_template_id")

    @config_template_id.setter
    def config_template_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "config_template_id", value)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "custom_fields")

    @custom_fields.setter
    def custom_fields(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_fields", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="deviceId")
    def device_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "device_id")

    @device_id.setter
    def device_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "device_id", value)

    @_builtins.property
    @pulumi.getter(name="deviceTypeId")
    def device_type_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "device_type_id")

    @device_type_id.setter
    def device_type_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "device_type_id", value)

    @_builtins.property
    @pulumi.getter(name="localContextData")
    def local_context_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        This is best managed through the use of <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> and a map of settings.
        """
        return pulumi.get(self, "local_context_data")

    @local_context_data.setter
    def local_context_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "local_context_data", value)

    @_builtins.property
    @pulumi.getter(name="locationId")
    def location_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "location_id")

    @location_id.setter
    def location_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "location_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="platformId")
    def platform_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "platform_id")

    @platform_id.setter
    def platform_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "platform_id", value)

    @_builtins.property
    @pulumi.getter(name="primaryIpv4")
    def primary_ipv4(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "primary_ipv4")

    @primary_ipv4.setter
    def primary_ipv4(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "primary_ipv4", value)

    @_builtins.property
    @pulumi.getter(name="primaryIpv6")
    def primary_ipv6(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "primary_ipv6")

    @primary_ipv6.setter
    def primary_ipv6(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "primary_ipv6", value)

    @_builtins.property
    @pulumi.getter(name="rackFace")
    def rack_face(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`front`" pulumi-lang-dotnet="`Front`" pulumi-lang-go="`front`" pulumi-lang-python="`front`" pulumi-lang-yaml="`front`" pulumi-lang-java="`front`">`front`</span> and <span pulumi-lang-nodejs="`rear`" pulumi-lang-dotnet="`Rear`" pulumi-lang-go="`rear`" pulumi-lang-python="`rear`" pulumi-lang-yaml="`rear`" pulumi-lang-java="`rear`">`rear`</span>. Required when <span pulumi-lang-nodejs="`rackPosition`" pulumi-lang-dotnet="`RackPosition`" pulumi-lang-go="`rackPosition`" pulumi-lang-python="`rack_position`" pulumi-lang-yaml="`rackPosition`" pulumi-lang-java="`rackPosition`">`rack_position`</span> is set.
        """
        return pulumi.get(self, "rack_face")

    @rack_face.setter
    def rack_face(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rack_face", value)

    @_builtins.property
    @pulumi.getter(name="rackId")
    def rack_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "rack_id")

    @rack_id.setter
    def rack_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "rack_id", value)

    @_builtins.property
    @pulumi.getter(name="rackPosition")
    def rack_position(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "rack_position")

    @rack_position.setter
    def rack_position(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "rack_position", value)

    @_builtins.property
    @pulumi.getter(name="roleId")
    def role_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "role_id")

    @role_id.setter
    def role_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "role_id", value)

    @_builtins.property
    @pulumi.getter
    def serial(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "serial")

    @serial.setter
    def serial(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "serial", value)

    @_builtins.property
    @pulumi.getter(name="siteId")
    def site_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "site_id")

    @site_id.setter
    def site_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "site_id", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`offline`" pulumi-lang-dotnet="`Offline`" pulumi-lang-go="`offline`" pulumi-lang-python="`offline`" pulumi-lang-yaml="`offline`" pulumi-lang-java="`offline`">`offline`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staged`" pulumi-lang-dotnet="`Staged`" pulumi-lang-go="`staged`" pulumi-lang-python="`staged`" pulumi-lang-yaml="`staged`" pulumi-lang-java="`staged`">`staged`</span>, <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`">`failed`</span>, <span pulumi-lang-nodejs="`inventory`" pulumi-lang-dotnet="`Inventory`" pulumi-lang-go="`inventory`" pulumi-lang-python="`inventory`" pulumi-lang-yaml="`inventory`" pulumi-lang-java="`inventory`">`inventory`</span> and <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags_alls")

    @tags_alls.setter
    def tags_alls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags_alls", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter(name="virtualChassisId")
    def virtual_chassis_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        return pulumi.get(self, "virtual_chassis_id")

    @virtual_chassis_id.setter
    def virtual_chassis_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "virtual_chassis_id", value)

    @_builtins.property
    @pulumi.getter(name="virtualChassisMaster")
    def virtual_chassis_master(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        return pulumi.get(self, "virtual_chassis_master")

    @virtual_chassis_master.setter
    def virtual_chassis_master(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "virtual_chassis_master", value)

    @_builtins.property
    @pulumi.getter(name="virtualChassisPosition")
    def virtual_chassis_position(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "virtual_chassis_position")

    @virtual_chassis_position.setter
    def virtual_chassis_position(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "virtual_chassis_position", value)

    @_builtins.property
    @pulumi.getter(name="virtualChassisPriority")
    def virtual_chassis_priority(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "virtual_chassis_priority")

    @virtual_chassis_priority.setter
    def virtual_chassis_priority(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "virtual_chassis_priority", value)


@pulumi.type_token("netbox:index/device:Device")
class Device(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 asset_tag: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_id: Optional[pulumi.Input[_builtins.float]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 config_template_id: Optional[pulumi.Input[_builtins.float]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 device_id: Optional[pulumi.Input[_builtins.str]] = None,
                 device_type_id: Optional[pulumi.Input[_builtins.float]] = None,
                 local_context_data: Optional[pulumi.Input[_builtins.str]] = None,
                 location_id: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 platform_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_face: Optional[pulumi.Input[_builtins.str]] = None,
                 rack_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_position: Optional[pulumi.Input[_builtins.float]] = None,
                 role_id: Optional[pulumi.Input[_builtins.float]] = None,
                 serial: Optional[pulumi.Input[_builtins.str]] = None,
                 site_id: Optional[pulumi.Input[_builtins.float]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_id: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_master: Optional[pulumi.Input[_builtins.bool]] = None,
                 virtual_chassis_position: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_priority: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        """
        Create a Device resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] local_context_data: This is best managed through the use of <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> and a map of settings.
        :param pulumi.Input[_builtins.str] rack_face: Valid values are <span pulumi-lang-nodejs="`front`" pulumi-lang-dotnet="`Front`" pulumi-lang-go="`front`" pulumi-lang-python="`front`" pulumi-lang-yaml="`front`" pulumi-lang-java="`front`">`front`</span> and <span pulumi-lang-nodejs="`rear`" pulumi-lang-dotnet="`Rear`" pulumi-lang-go="`rear`" pulumi-lang-python="`rear`" pulumi-lang-yaml="`rear`" pulumi-lang-java="`rear`">`rear`</span>. Required when <span pulumi-lang-nodejs="`rackPosition`" pulumi-lang-dotnet="`RackPosition`" pulumi-lang-go="`rackPosition`" pulumi-lang-python="`rack_position`" pulumi-lang-yaml="`rackPosition`" pulumi-lang-java="`rackPosition`">`rack_position`</span> is set.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`offline`" pulumi-lang-dotnet="`Offline`" pulumi-lang-go="`offline`" pulumi-lang-python="`offline`" pulumi-lang-yaml="`offline`" pulumi-lang-java="`offline`">`offline`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staged`" pulumi-lang-dotnet="`Staged`" pulumi-lang-go="`staged`" pulumi-lang-python="`staged`" pulumi-lang-yaml="`staged`" pulumi-lang-java="`staged`">`staged`</span>, <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`">`failed`</span>, <span pulumi-lang-nodejs="`inventory`" pulumi-lang-dotnet="`Inventory`" pulumi-lang-go="`inventory`" pulumi-lang-python="`inventory`" pulumi-lang-yaml="`inventory`" pulumi-lang-java="`inventory`">`inventory`</span> and <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        :param pulumi.Input[_builtins.float] virtual_chassis_id: Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        :param pulumi.Input[_builtins.bool] virtual_chassis_master: Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DeviceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Device resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param DeviceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DeviceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 asset_tag: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_id: Optional[pulumi.Input[_builtins.float]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 config_template_id: Optional[pulumi.Input[_builtins.float]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 device_id: Optional[pulumi.Input[_builtins.str]] = None,
                 device_type_id: Optional[pulumi.Input[_builtins.float]] = None,
                 local_context_data: Optional[pulumi.Input[_builtins.str]] = None,
                 location_id: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 platform_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_face: Optional[pulumi.Input[_builtins.str]] = None,
                 rack_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_position: Optional[pulumi.Input[_builtins.float]] = None,
                 role_id: Optional[pulumi.Input[_builtins.float]] = None,
                 serial: Optional[pulumi.Input[_builtins.str]] = None,
                 site_id: Optional[pulumi.Input[_builtins.float]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_id: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_master: Optional[pulumi.Input[_builtins.bool]] = None,
                 virtual_chassis_position: Optional[pulumi.Input[_builtins.float]] = None,
                 virtual_chassis_priority: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DeviceArgs.__new__(DeviceArgs)

            __props__.__dict__["asset_tag"] = asset_tag
            __props__.__dict__["cluster_id"] = cluster_id
            __props__.__dict__["comments"] = comments
            __props__.__dict__["config_template_id"] = config_template_id
            __props__.__dict__["custom_fields"] = custom_fields
            __props__.__dict__["description"] = description
            __props__.__dict__["device_id"] = device_id
            if device_type_id is None and not opts.urn:
                raise TypeError("Missing required property 'device_type_id'")
            __props__.__dict__["device_type_id"] = device_type_id
            __props__.__dict__["local_context_data"] = local_context_data
            __props__.__dict__["location_id"] = location_id
            __props__.__dict__["name"] = name
            __props__.__dict__["platform_id"] = platform_id
            __props__.__dict__["rack_face"] = rack_face
            __props__.__dict__["rack_id"] = rack_id
            __props__.__dict__["rack_position"] = rack_position
            if role_id is None and not opts.urn:
                raise TypeError("Missing required property 'role_id'")
            __props__.__dict__["role_id"] = role_id
            __props__.__dict__["serial"] = serial
            if site_id is None and not opts.urn:
                raise TypeError("Missing required property 'site_id'")
            __props__.__dict__["site_id"] = site_id
            __props__.__dict__["status"] = status
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_id"] = tenant_id
            __props__.__dict__["virtual_chassis_id"] = virtual_chassis_id
            __props__.__dict__["virtual_chassis_master"] = virtual_chassis_master
            __props__.__dict__["virtual_chassis_position"] = virtual_chassis_position
            __props__.__dict__["virtual_chassis_priority"] = virtual_chassis_priority
            __props__.__dict__["primary_ipv4"] = None
            __props__.__dict__["primary_ipv6"] = None
            __props__.__dict__["tags_alls"] = None
        super(Device, __self__).__init__(
            'netbox:index/device:Device',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            asset_tag: Optional[pulumi.Input[_builtins.str]] = None,
            cluster_id: Optional[pulumi.Input[_builtins.float]] = None,
            comments: Optional[pulumi.Input[_builtins.str]] = None,
            config_template_id: Optional[pulumi.Input[_builtins.float]] = None,
            custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            device_id: Optional[pulumi.Input[_builtins.str]] = None,
            device_type_id: Optional[pulumi.Input[_builtins.float]] = None,
            local_context_data: Optional[pulumi.Input[_builtins.str]] = None,
            location_id: Optional[pulumi.Input[_builtins.float]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            platform_id: Optional[pulumi.Input[_builtins.float]] = None,
            primary_ipv4: Optional[pulumi.Input[_builtins.float]] = None,
            primary_ipv6: Optional[pulumi.Input[_builtins.float]] = None,
            rack_face: Optional[pulumi.Input[_builtins.str]] = None,
            rack_id: Optional[pulumi.Input[_builtins.float]] = None,
            rack_position: Optional[pulumi.Input[_builtins.float]] = None,
            role_id: Optional[pulumi.Input[_builtins.float]] = None,
            serial: Optional[pulumi.Input[_builtins.str]] = None,
            site_id: Optional[pulumi.Input[_builtins.float]] = None,
            status: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
            virtual_chassis_id: Optional[pulumi.Input[_builtins.float]] = None,
            virtual_chassis_master: Optional[pulumi.Input[_builtins.bool]] = None,
            virtual_chassis_position: Optional[pulumi.Input[_builtins.float]] = None,
            virtual_chassis_priority: Optional[pulumi.Input[_builtins.float]] = None) -> 'Device':
        """
        Get an existing Device resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] local_context_data: This is best managed through the use of <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> and a map of settings.
        :param pulumi.Input[_builtins.str] rack_face: Valid values are <span pulumi-lang-nodejs="`front`" pulumi-lang-dotnet="`Front`" pulumi-lang-go="`front`" pulumi-lang-python="`front`" pulumi-lang-yaml="`front`" pulumi-lang-java="`front`">`front`</span> and <span pulumi-lang-nodejs="`rear`" pulumi-lang-dotnet="`Rear`" pulumi-lang-go="`rear`" pulumi-lang-python="`rear`" pulumi-lang-yaml="`rear`" pulumi-lang-java="`rear`">`rear`</span>. Required when <span pulumi-lang-nodejs="`rackPosition`" pulumi-lang-dotnet="`RackPosition`" pulumi-lang-go="`rackPosition`" pulumi-lang-python="`rack_position`" pulumi-lang-yaml="`rackPosition`" pulumi-lang-java="`rackPosition`">`rack_position`</span> is set.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`offline`" pulumi-lang-dotnet="`Offline`" pulumi-lang-go="`offline`" pulumi-lang-python="`offline`" pulumi-lang-yaml="`offline`" pulumi-lang-java="`offline`">`offline`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staged`" pulumi-lang-dotnet="`Staged`" pulumi-lang-go="`staged`" pulumi-lang-python="`staged`" pulumi-lang-yaml="`staged`" pulumi-lang-java="`staged`">`staged`</span>, <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`">`failed`</span>, <span pulumi-lang-nodejs="`inventory`" pulumi-lang-dotnet="`Inventory`" pulumi-lang-go="`inventory`" pulumi-lang-python="`inventory`" pulumi-lang-yaml="`inventory`" pulumi-lang-java="`inventory`">`inventory`</span> and <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        :param pulumi.Input[_builtins.float] virtual_chassis_id: Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        :param pulumi.Input[_builtins.bool] virtual_chassis_master: Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DeviceState.__new__(_DeviceState)

        __props__.__dict__["asset_tag"] = asset_tag
        __props__.__dict__["cluster_id"] = cluster_id
        __props__.__dict__["comments"] = comments
        __props__.__dict__["config_template_id"] = config_template_id
        __props__.__dict__["custom_fields"] = custom_fields
        __props__.__dict__["description"] = description
        __props__.__dict__["device_id"] = device_id
        __props__.__dict__["device_type_id"] = device_type_id
        __props__.__dict__["local_context_data"] = local_context_data
        __props__.__dict__["location_id"] = location_id
        __props__.__dict__["name"] = name
        __props__.__dict__["platform_id"] = platform_id
        __props__.__dict__["primary_ipv4"] = primary_ipv4
        __props__.__dict__["primary_ipv6"] = primary_ipv6
        __props__.__dict__["rack_face"] = rack_face
        __props__.__dict__["rack_id"] = rack_id
        __props__.__dict__["rack_position"] = rack_position
        __props__.__dict__["role_id"] = role_id
        __props__.__dict__["serial"] = serial
        __props__.__dict__["site_id"] = site_id
        __props__.__dict__["status"] = status
        __props__.__dict__["tags"] = tags
        __props__.__dict__["tags_alls"] = tags_alls
        __props__.__dict__["tenant_id"] = tenant_id
        __props__.__dict__["virtual_chassis_id"] = virtual_chassis_id
        __props__.__dict__["virtual_chassis_master"] = virtual_chassis_master
        __props__.__dict__["virtual_chassis_position"] = virtual_chassis_position
        __props__.__dict__["virtual_chassis_priority"] = virtual_chassis_priority
        return Device(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="assetTag")
    def asset_tag(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "asset_tag")

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "cluster_id")

    @_builtins.property
    @pulumi.getter
    def comments(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "comments")

    @_builtins.property
    @pulumi.getter(name="configTemplateId")
    def config_template_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "config_template_id")

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "custom_fields")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="deviceId")
    def device_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "device_id")

    @_builtins.property
    @pulumi.getter(name="deviceTypeId")
    def device_type_id(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "device_type_id")

    @_builtins.property
    @pulumi.getter(name="localContextData")
    def local_context_data(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        This is best managed through the use of <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> and a map of settings.
        """
        return pulumi.get(self, "local_context_data")

    @_builtins.property
    @pulumi.getter(name="locationId")
    def location_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "location_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="platformId")
    def platform_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "platform_id")

    @_builtins.property
    @pulumi.getter(name="primaryIpv4")
    def primary_ipv4(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "primary_ipv4")

    @_builtins.property
    @pulumi.getter(name="primaryIpv6")
    def primary_ipv6(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "primary_ipv6")

    @_builtins.property
    @pulumi.getter(name="rackFace")
    def rack_face(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`front`" pulumi-lang-dotnet="`Front`" pulumi-lang-go="`front`" pulumi-lang-python="`front`" pulumi-lang-yaml="`front`" pulumi-lang-java="`front`">`front`</span> and <span pulumi-lang-nodejs="`rear`" pulumi-lang-dotnet="`Rear`" pulumi-lang-go="`rear`" pulumi-lang-python="`rear`" pulumi-lang-yaml="`rear`" pulumi-lang-java="`rear`">`rear`</span>. Required when <span pulumi-lang-nodejs="`rackPosition`" pulumi-lang-dotnet="`RackPosition`" pulumi-lang-go="`rackPosition`" pulumi-lang-python="`rack_position`" pulumi-lang-yaml="`rackPosition`" pulumi-lang-java="`rackPosition`">`rack_position`</span> is set.
        """
        return pulumi.get(self, "rack_face")

    @_builtins.property
    @pulumi.getter(name="rackId")
    def rack_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "rack_id")

    @_builtins.property
    @pulumi.getter(name="rackPosition")
    def rack_position(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "rack_position")

    @_builtins.property
    @pulumi.getter(name="roleId")
    def role_id(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "role_id")

    @_builtins.property
    @pulumi.getter
    def serial(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "serial")

    @_builtins.property
    @pulumi.getter(name="siteId")
    def site_id(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "site_id")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`offline`" pulumi-lang-dotnet="`Offline`" pulumi-lang-go="`offline`" pulumi-lang-python="`offline`" pulumi-lang-yaml="`offline`" pulumi-lang-java="`offline`">`offline`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staged`" pulumi-lang-dotnet="`Staged`" pulumi-lang-go="`staged`" pulumi-lang-python="`staged`" pulumi-lang-yaml="`staged`" pulumi-lang-java="`staged`">`staged`</span>, <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`">`failed`</span>, <span pulumi-lang-nodejs="`inventory`" pulumi-lang-dotnet="`Inventory`" pulumi-lang-go="`inventory`" pulumi-lang-python="`inventory`" pulumi-lang-yaml="`inventory`" pulumi-lang-java="`inventory`">`inventory`</span> and <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "tags_alls")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter(name="virtualChassisId")
    def virtual_chassis_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        return pulumi.get(self, "virtual_chassis_id")

    @_builtins.property
    @pulumi.getter(name="virtualChassisMaster")
    def virtual_chassis_master(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Required when <span pulumi-lang-nodejs="`virtualChassisMaster`" pulumi-lang-dotnet="`VirtualChassisMaster`" pulumi-lang-go="`virtualChassisMaster`" pulumi-lang-python="`virtual_chassis_master`" pulumi-lang-yaml="`virtualChassisMaster`" pulumi-lang-java="`virtualChassisMaster`">`virtual_chassis_master`</span> and <span pulumi-lang-nodejs="`virtualChassisId`" pulumi-lang-dotnet="`VirtualChassisId`" pulumi-lang-go="`virtualChassisId`" pulumi-lang-python="`virtual_chassis_id`" pulumi-lang-yaml="`virtualChassisId`" pulumi-lang-java="`virtualChassisId`">`virtual_chassis_id`</span> is set.
        """
        return pulumi.get(self, "virtual_chassis_master")

    @_builtins.property
    @pulumi.getter(name="virtualChassisPosition")
    def virtual_chassis_position(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "virtual_chassis_position")

    @_builtins.property
    @pulumi.getter(name="virtualChassisPriority")
    def virtual_chassis_priority(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "virtual_chassis_priority")

