# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetVrfsResult',
    'AwaitableGetVrfsResult',
    'get_vrfs',
    'get_vrfs_output',
]

@pulumi.output_type
class GetVrfsResult:
    """
    A collection of values returned by getVrfs.
    """
    def __init__(__self__, filters=None, id=None, limit=None, vrfs=None):
        if filters and not isinstance(filters, list):
            raise TypeError("Expected argument 'filters' to be a list")
        pulumi.set(__self__, "filters", filters)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if limit and not isinstance(limit, float):
            raise TypeError("Expected argument 'limit' to be a float")
        pulumi.set(__self__, "limit", limit)
        if vrfs and not isinstance(vrfs, list):
            raise TypeError("Expected argument 'vrfs' to be a list")
        pulumi.set(__self__, "vrfs", vrfs)

    @_builtins.property
    @pulumi.getter
    def filters(self) -> Optional[Sequence['outputs.GetVrfsFilterResult']]:
        return pulumi.get(self, "filters")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def limit(self) -> Optional[_builtins.float]:
        return pulumi.get(self, "limit")

    @_builtins.property
    @pulumi.getter
    def vrfs(self) -> Sequence['outputs.GetVrfsVrfResult']:
        return pulumi.get(self, "vrfs")


class AwaitableGetVrfsResult(GetVrfsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetVrfsResult(
            filters=self.filters,
            id=self.id,
            limit=self.limit,
            vrfs=self.vrfs)


def get_vrfs(filters: Optional[Sequence[Union['GetVrfsFilterArgs', 'GetVrfsFilterArgsDict']]] = None,
             id: Optional[_builtins.str] = None,
             limit: Optional[_builtins.float] = None,
             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetVrfsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['filters'] = filters
    __args__['id'] = id
    __args__['limit'] = limit
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('netbox:index/getVrfs:getVrfs', __args__, opts=opts, typ=GetVrfsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetVrfsResult(
        filters=pulumi.get(__ret__, 'filters'),
        id=pulumi.get(__ret__, 'id'),
        limit=pulumi.get(__ret__, 'limit'),
        vrfs=pulumi.get(__ret__, 'vrfs'))
def get_vrfs_output(filters: Optional[pulumi.Input[Optional[Sequence[Union['GetVrfsFilterArgs', 'GetVrfsFilterArgsDict']]]]] = None,
                    id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                    limit: Optional[pulumi.Input[Optional[_builtins.float]]] = None,
                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetVrfsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['filters'] = filters
    __args__['id'] = id
    __args__['limit'] = limit
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('netbox:index/getVrfs:getVrfs', __args__, opts=opts, typ=GetVrfsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetVrfsResult(
        filters=pulumi.get(__response__, 'filters'),
        id=pulumi.get(__response__, 'id'),
        limit=pulumi.get(__response__, 'limit'),
        vrfs=pulumi.get(__response__, 'vrfs')))
