# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PermissionArgs', 'Permission']

@pulumi.input_type
class PermissionArgs:
    def __init__(__self__, *,
                 actions: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 object_types: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 constraints: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 permission_id: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None):
        """
        The set of arguments for constructing a Permission resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] actions: A list actions that are allowed on the object types. Acceptable values are <span pulumi-lang-nodejs="`view`" pulumi-lang-dotnet="`View`" pulumi-lang-go="`view`" pulumi-lang-python="`view`" pulumi-lang-yaml="`view`" pulumi-lang-java="`view`">`view`</span>, <span pulumi-lang-nodejs="`add`" pulumi-lang-dotnet="`Add`" pulumi-lang-go="`add`" pulumi-lang-python="`add`" pulumi-lang-yaml="`add`" pulumi-lang-java="`add`">`add`</span>, <span pulumi-lang-nodejs="`change`" pulumi-lang-dotnet="`Change`" pulumi-lang-go="`change`" pulumi-lang-python="`change`" pulumi-lang-yaml="`change`" pulumi-lang-java="`change`">`change`</span>, or <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`">`delete`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] object_types: A list of object types that the permission object allows access to. Should be in a form the API can accept. For example: `circuits.provider`, `dcim.inventoryitem`, etc.
        :param pulumi.Input[_builtins.str] constraints: A JSON string of an arbitrary filter used to limit the granted action(s) to a specific subset of objects. For more information on correct syntax, see https://docs.netbox.dev/en/stable/administration/permissions/#constraints.
        :param pulumi.Input[_builtins.str] description: The description of the permission object.
        :param pulumi.Input[_builtins.bool] enabled: Whether the permission object is enabled or not. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] groups: A list of group IDs that have been assigned to this permission object.
        :param pulumi.Input[_builtins.str] name: The name of the permission object.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] users: A list of user IDs that have been assigned to this permission object.
        """
        pulumi.set(__self__, "actions", actions)
        pulumi.set(__self__, "object_types", object_types)
        if constraints is not None:
            pulumi.set(__self__, "constraints", constraints)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if permission_id is not None:
            pulumi.set(__self__, "permission_id", permission_id)
        if users is not None:
            pulumi.set(__self__, "users", users)

    @_builtins.property
    @pulumi.getter
    def actions(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        A list actions that are allowed on the object types. Acceptable values are <span pulumi-lang-nodejs="`view`" pulumi-lang-dotnet="`View`" pulumi-lang-go="`view`" pulumi-lang-python="`view`" pulumi-lang-yaml="`view`" pulumi-lang-java="`view`">`view`</span>, <span pulumi-lang-nodejs="`add`" pulumi-lang-dotnet="`Add`" pulumi-lang-go="`add`" pulumi-lang-python="`add`" pulumi-lang-yaml="`add`" pulumi-lang-java="`add`">`add`</span>, <span pulumi-lang-nodejs="`change`" pulumi-lang-dotnet="`Change`" pulumi-lang-go="`change`" pulumi-lang-python="`change`" pulumi-lang-yaml="`change`" pulumi-lang-java="`change`">`change`</span>, or <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`">`delete`</span>.
        """
        return pulumi.get(self, "actions")

    @actions.setter
    def actions(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "actions", value)

    @_builtins.property
    @pulumi.getter(name="objectTypes")
    def object_types(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        A list of object types that the permission object allows access to. Should be in a form the API can accept. For example: `circuits.provider`, `dcim.inventoryitem`, etc.
        """
        return pulumi.get(self, "object_types")

    @object_types.setter
    def object_types(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "object_types", value)

    @_builtins.property
    @pulumi.getter
    def constraints(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A JSON string of an arbitrary filter used to limit the granted action(s) to a specific subset of objects. For more information on correct syntax, see https://docs.netbox.dev/en/stable/administration/permissions/#constraints.
        """
        return pulumi.get(self, "constraints")

    @constraints.setter
    def constraints(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "constraints", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the permission object.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the permission object is enabled or not. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        """
        A list of group IDs that have been assigned to this permission object.
        """
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the permission object.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="permissionId")
    def permission_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "permission_id")

    @permission_id.setter
    def permission_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "permission_id", value)

    @_builtins.property
    @pulumi.getter
    def users(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        """
        A list of user IDs that have been assigned to this permission object.
        """
        return pulumi.get(self, "users")

    @users.setter
    def users(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "users", value)


@pulumi.input_type
class _PermissionState:
    def __init__(__self__, *,
                 actions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 constraints: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 object_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 permission_id: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None):
        """
        Input properties used for looking up and filtering Permission resources.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] actions: A list actions that are allowed on the object types. Acceptable values are <span pulumi-lang-nodejs="`view`" pulumi-lang-dotnet="`View`" pulumi-lang-go="`view`" pulumi-lang-python="`view`" pulumi-lang-yaml="`view`" pulumi-lang-java="`view`">`view`</span>, <span pulumi-lang-nodejs="`add`" pulumi-lang-dotnet="`Add`" pulumi-lang-go="`add`" pulumi-lang-python="`add`" pulumi-lang-yaml="`add`" pulumi-lang-java="`add`">`add`</span>, <span pulumi-lang-nodejs="`change`" pulumi-lang-dotnet="`Change`" pulumi-lang-go="`change`" pulumi-lang-python="`change`" pulumi-lang-yaml="`change`" pulumi-lang-java="`change`">`change`</span>, or <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`">`delete`</span>.
        :param pulumi.Input[_builtins.str] constraints: A JSON string of an arbitrary filter used to limit the granted action(s) to a specific subset of objects. For more information on correct syntax, see https://docs.netbox.dev/en/stable/administration/permissions/#constraints.
        :param pulumi.Input[_builtins.str] description: The description of the permission object.
        :param pulumi.Input[_builtins.bool] enabled: Whether the permission object is enabled or not. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] groups: A list of group IDs that have been assigned to this permission object.
        :param pulumi.Input[_builtins.str] name: The name of the permission object.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] object_types: A list of object types that the permission object allows access to. Should be in a form the API can accept. For example: `circuits.provider`, `dcim.inventoryitem`, etc.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] users: A list of user IDs that have been assigned to this permission object.
        """
        if actions is not None:
            pulumi.set(__self__, "actions", actions)
        if constraints is not None:
            pulumi.set(__self__, "constraints", constraints)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if object_types is not None:
            pulumi.set(__self__, "object_types", object_types)
        if permission_id is not None:
            pulumi.set(__self__, "permission_id", permission_id)
        if users is not None:
            pulumi.set(__self__, "users", users)

    @_builtins.property
    @pulumi.getter
    def actions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list actions that are allowed on the object types. Acceptable values are <span pulumi-lang-nodejs="`view`" pulumi-lang-dotnet="`View`" pulumi-lang-go="`view`" pulumi-lang-python="`view`" pulumi-lang-yaml="`view`" pulumi-lang-java="`view`">`view`</span>, <span pulumi-lang-nodejs="`add`" pulumi-lang-dotnet="`Add`" pulumi-lang-go="`add`" pulumi-lang-python="`add`" pulumi-lang-yaml="`add`" pulumi-lang-java="`add`">`add`</span>, <span pulumi-lang-nodejs="`change`" pulumi-lang-dotnet="`Change`" pulumi-lang-go="`change`" pulumi-lang-python="`change`" pulumi-lang-yaml="`change`" pulumi-lang-java="`change`">`change`</span>, or <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`">`delete`</span>.
        """
        return pulumi.get(self, "actions")

    @actions.setter
    def actions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "actions", value)

    @_builtins.property
    @pulumi.getter
    def constraints(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A JSON string of an arbitrary filter used to limit the granted action(s) to a specific subset of objects. For more information on correct syntax, see https://docs.netbox.dev/en/stable/administration/permissions/#constraints.
        """
        return pulumi.get(self, "constraints")

    @constraints.setter
    def constraints(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "constraints", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the permission object.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the permission object is enabled or not. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        """
        A list of group IDs that have been assigned to this permission object.
        """
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the permission object.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="objectTypes")
    def object_types(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of object types that the permission object allows access to. Should be in a form the API can accept. For example: `circuits.provider`, `dcim.inventoryitem`, etc.
        """
        return pulumi.get(self, "object_types")

    @object_types.setter
    def object_types(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "object_types", value)

    @_builtins.property
    @pulumi.getter(name="permissionId")
    def permission_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "permission_id")

    @permission_id.setter
    def permission_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "permission_id", value)

    @_builtins.property
    @pulumi.getter
    def users(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        """
        A list of user IDs that have been assigned to this permission object.
        """
        return pulumi.get(self, "users")

    @users.setter
    def users(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "users", value)


@pulumi.type_token("netbox:index/permission:Permission")
class Permission(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 actions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 constraints: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 object_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 permission_id: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 __props__=None):
        """
        Create a Permission resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] actions: A list actions that are allowed on the object types. Acceptable values are <span pulumi-lang-nodejs="`view`" pulumi-lang-dotnet="`View`" pulumi-lang-go="`view`" pulumi-lang-python="`view`" pulumi-lang-yaml="`view`" pulumi-lang-java="`view`">`view`</span>, <span pulumi-lang-nodejs="`add`" pulumi-lang-dotnet="`Add`" pulumi-lang-go="`add`" pulumi-lang-python="`add`" pulumi-lang-yaml="`add`" pulumi-lang-java="`add`">`add`</span>, <span pulumi-lang-nodejs="`change`" pulumi-lang-dotnet="`Change`" pulumi-lang-go="`change`" pulumi-lang-python="`change`" pulumi-lang-yaml="`change`" pulumi-lang-java="`change`">`change`</span>, or <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`">`delete`</span>.
        :param pulumi.Input[_builtins.str] constraints: A JSON string of an arbitrary filter used to limit the granted action(s) to a specific subset of objects. For more information on correct syntax, see https://docs.netbox.dev/en/stable/administration/permissions/#constraints.
        :param pulumi.Input[_builtins.str] description: The description of the permission object.
        :param pulumi.Input[_builtins.bool] enabled: Whether the permission object is enabled or not. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] groups: A list of group IDs that have been assigned to this permission object.
        :param pulumi.Input[_builtins.str] name: The name of the permission object.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] object_types: A list of object types that the permission object allows access to. Should be in a form the API can accept. For example: `circuits.provider`, `dcim.inventoryitem`, etc.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] users: A list of user IDs that have been assigned to this permission object.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PermissionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Permission resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PermissionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PermissionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 actions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 constraints: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 object_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 permission_id: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PermissionArgs.__new__(PermissionArgs)

            if actions is None and not opts.urn:
                raise TypeError("Missing required property 'actions'")
            __props__.__dict__["actions"] = actions
            __props__.__dict__["constraints"] = constraints
            __props__.__dict__["description"] = description
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["groups"] = groups
            __props__.__dict__["name"] = name
            if object_types is None and not opts.urn:
                raise TypeError("Missing required property 'object_types'")
            __props__.__dict__["object_types"] = object_types
            __props__.__dict__["permission_id"] = permission_id
            __props__.__dict__["users"] = users
        super(Permission, __self__).__init__(
            'netbox:index/permission:Permission',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            actions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            constraints: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            object_types: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            permission_id: Optional[pulumi.Input[_builtins.str]] = None,
            users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None) -> 'Permission':
        """
        Get an existing Permission resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] actions: A list actions that are allowed on the object types. Acceptable values are <span pulumi-lang-nodejs="`view`" pulumi-lang-dotnet="`View`" pulumi-lang-go="`view`" pulumi-lang-python="`view`" pulumi-lang-yaml="`view`" pulumi-lang-java="`view`">`view`</span>, <span pulumi-lang-nodejs="`add`" pulumi-lang-dotnet="`Add`" pulumi-lang-go="`add`" pulumi-lang-python="`add`" pulumi-lang-yaml="`add`" pulumi-lang-java="`add`">`add`</span>, <span pulumi-lang-nodejs="`change`" pulumi-lang-dotnet="`Change`" pulumi-lang-go="`change`" pulumi-lang-python="`change`" pulumi-lang-yaml="`change`" pulumi-lang-java="`change`">`change`</span>, or <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`">`delete`</span>.
        :param pulumi.Input[_builtins.str] constraints: A JSON string of an arbitrary filter used to limit the granted action(s) to a specific subset of objects. For more information on correct syntax, see https://docs.netbox.dev/en/stable/administration/permissions/#constraints.
        :param pulumi.Input[_builtins.str] description: The description of the permission object.
        :param pulumi.Input[_builtins.bool] enabled: Whether the permission object is enabled or not. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] groups: A list of group IDs that have been assigned to this permission object.
        :param pulumi.Input[_builtins.str] name: The name of the permission object.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] object_types: A list of object types that the permission object allows access to. Should be in a form the API can accept. For example: `circuits.provider`, `dcim.inventoryitem`, etc.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] users: A list of user IDs that have been assigned to this permission object.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PermissionState.__new__(_PermissionState)

        __props__.__dict__["actions"] = actions
        __props__.__dict__["constraints"] = constraints
        __props__.__dict__["description"] = description
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["groups"] = groups
        __props__.__dict__["name"] = name
        __props__.__dict__["object_types"] = object_types
        __props__.__dict__["permission_id"] = permission_id
        __props__.__dict__["users"] = users
        return Permission(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def actions(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        A list actions that are allowed on the object types. Acceptable values are <span pulumi-lang-nodejs="`view`" pulumi-lang-dotnet="`View`" pulumi-lang-go="`view`" pulumi-lang-python="`view`" pulumi-lang-yaml="`view`" pulumi-lang-java="`view`">`view`</span>, <span pulumi-lang-nodejs="`add`" pulumi-lang-dotnet="`Add`" pulumi-lang-go="`add`" pulumi-lang-python="`add`" pulumi-lang-yaml="`add`" pulumi-lang-java="`add`">`add`</span>, <span pulumi-lang-nodejs="`change`" pulumi-lang-dotnet="`Change`" pulumi-lang-go="`change`" pulumi-lang-python="`change`" pulumi-lang-yaml="`change`" pulumi-lang-java="`change`">`change`</span>, or <span pulumi-lang-nodejs="`delete`" pulumi-lang-dotnet="`Delete`" pulumi-lang-go="`delete`" pulumi-lang-python="`delete`" pulumi-lang-yaml="`delete`" pulumi-lang-java="`delete`">`delete`</span>.
        """
        return pulumi.get(self, "actions")

    @_builtins.property
    @pulumi.getter
    def constraints(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A JSON string of an arbitrary filter used to limit the granted action(s) to a specific subset of objects. For more information on correct syntax, see https://docs.netbox.dev/en/stable/administration/permissions/#constraints.
        """
        return pulumi.get(self, "constraints")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The description of the permission object.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the permission object is enabled or not. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`">`true`</span>.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Output[Optional[Sequence[_builtins.float]]]:
        """
        A list of group IDs that have been assigned to this permission object.
        """
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the permission object.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="objectTypes")
    def object_types(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        A list of object types that the permission object allows access to. Should be in a form the API can accept. For example: `circuits.provider`, `dcim.inventoryitem`, etc.
        """
        return pulumi.get(self, "object_types")

    @_builtins.property
    @pulumi.getter(name="permissionId")
    def permission_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "permission_id")

    @_builtins.property
    @pulumi.getter
    def users(self) -> pulumi.Output[Optional[Sequence[_builtins.float]]]:
        """
        A list of user IDs that have been assigned to this permission object.
        """
        return pulumi.get(self, "users")

