# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['RackReservationArgs', 'RackReservation']

@pulumi.input_type
class RackReservationArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[_builtins.str],
                 rack_id: pulumi.Input[_builtins.float],
                 units: pulumi.Input[Sequence[pulumi.Input[_builtins.float]]],
                 user_id: pulumi.Input[_builtins.float],
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 rack_reservation_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None):
        """
        The set of arguments for constructing a RackReservation resource.
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "rack_id", rack_id)
        pulumi.set(__self__, "units", units)
        pulumi.set(__self__, "user_id", user_id)
        if comments is not None:
            pulumi.set(__self__, "comments", comments)
        if rack_reservation_id is not None:
            pulumi.set(__self__, "rack_reservation_id", rack_reservation_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="rackId")
    def rack_id(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "rack_id")

    @rack_id.setter
    def rack_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "rack_id", value)

    @_builtins.property
    @pulumi.getter
    def units(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]:
        return pulumi.get(self, "units")

    @units.setter
    def units(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]):
        pulumi.set(self, "units", value)

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "user_id", value)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "comments")

    @comments.setter
    def comments(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "comments", value)

    @_builtins.property
    @pulumi.getter(name="rackReservationId")
    def rack_reservation_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "rack_reservation_id")

    @rack_reservation_id.setter
    def rack_reservation_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rack_reservation_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)


@pulumi.input_type
class _RackReservationState:
    def __init__(__self__, *,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 rack_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_reservation_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 units: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 user_id: Optional[pulumi.Input[_builtins.float]] = None):
        """
        Input properties used for looking up and filtering RackReservation resources.
        """
        if comments is not None:
            pulumi.set(__self__, "comments", comments)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if rack_id is not None:
            pulumi.set(__self__, "rack_id", rack_id)
        if rack_reservation_id is not None:
            pulumi.set(__self__, "rack_reservation_id", rack_reservation_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tags_alls is not None:
            pulumi.set(__self__, "tags_alls", tags_alls)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if units is not None:
            pulumi.set(__self__, "units", units)
        if user_id is not None:
            pulumi.set(__self__, "user_id", user_id)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "comments")

    @comments.setter
    def comments(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "comments", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="rackId")
    def rack_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "rack_id")

    @rack_id.setter
    def rack_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "rack_id", value)

    @_builtins.property
    @pulumi.getter(name="rackReservationId")
    def rack_reservation_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "rack_reservation_id")

    @rack_reservation_id.setter
    def rack_reservation_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rack_reservation_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags_alls")

    @tags_alls.setter
    def tags_alls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags_alls", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter
    def units(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        return pulumi.get(self, "units")

    @units.setter
    def units(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "units", value)

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "user_id", value)


@pulumi.type_token("netbox:index/rackReservation:RackReservation")
class RackReservation(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 rack_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_reservation_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 units: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 user_id: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        """
        Create a RackReservation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RackReservationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a RackReservation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param RackReservationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RackReservationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 rack_id: Optional[pulumi.Input[_builtins.float]] = None,
                 rack_reservation_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 units: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 user_id: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RackReservationArgs.__new__(RackReservationArgs)

            __props__.__dict__["comments"] = comments
            if description is None and not opts.urn:
                raise TypeError("Missing required property 'description'")
            __props__.__dict__["description"] = description
            if rack_id is None and not opts.urn:
                raise TypeError("Missing required property 'rack_id'")
            __props__.__dict__["rack_id"] = rack_id
            __props__.__dict__["rack_reservation_id"] = rack_reservation_id
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_id"] = tenant_id
            if units is None and not opts.urn:
                raise TypeError("Missing required property 'units'")
            __props__.__dict__["units"] = units
            if user_id is None and not opts.urn:
                raise TypeError("Missing required property 'user_id'")
            __props__.__dict__["user_id"] = user_id
            __props__.__dict__["tags_alls"] = None
        super(RackReservation, __self__).__init__(
            'netbox:index/rackReservation:RackReservation',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            comments: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            rack_id: Optional[pulumi.Input[_builtins.float]] = None,
            rack_reservation_id: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
            units: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
            user_id: Optional[pulumi.Input[_builtins.float]] = None) -> 'RackReservation':
        """
        Get an existing RackReservation resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RackReservationState.__new__(_RackReservationState)

        __props__.__dict__["comments"] = comments
        __props__.__dict__["description"] = description
        __props__.__dict__["rack_id"] = rack_id
        __props__.__dict__["rack_reservation_id"] = rack_reservation_id
        __props__.__dict__["tags"] = tags
        __props__.__dict__["tags_alls"] = tags_alls
        __props__.__dict__["tenant_id"] = tenant_id
        __props__.__dict__["units"] = units
        __props__.__dict__["user_id"] = user_id
        return RackReservation(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "comments")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="rackId")
    def rack_id(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "rack_id")

    @_builtins.property
    @pulumi.getter(name="rackReservationId")
    def rack_reservation_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "rack_reservation_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "tags_alls")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter
    def units(self) -> pulumi.Output[Sequence[_builtins.float]]:
        return pulumi.get(self, "units")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "user_id")

