# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ServiceArgs', 'Service']

@pulumi.input_type
class ServiceArgs:
    def __init__(__self__, *,
                 protocol: pulumi.Input[_builtins.str],
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 device_id: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.float]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 service_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 virtual_machine_id: Optional[pulumi.Input[_builtins.float]] = None):
        """
        The set of arguments for constructing a Service resource.
        :param pulumi.Input[_builtins.str] protocol: Valid values are <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`">`tcp`</span>, <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`">`udp`</span> and <span pulumi-lang-nodejs="`sctp`" pulumi-lang-dotnet="`Sctp`" pulumi-lang-go="`sctp`" pulumi-lang-python="`sctp`" pulumi-lang-yaml="`sctp`" pulumi-lang-java="`sctp`">`sctp`</span>.
        :param pulumi.Input[_builtins.float] device_id: Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        :param pulumi.Input[_builtins.float] port: Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] ports: Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        :param pulumi.Input[_builtins.float] virtual_machine_id: Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        pulumi.set(__self__, "protocol", protocol)
        if custom_fields is not None:
            pulumi.set(__self__, "custom_fields", custom_fields)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if device_id is not None:
            pulumi.set(__self__, "device_id", device_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if port is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""port is deprecated: Deprecated""")
        if port is not None:
            pulumi.set(__self__, "port", port)
        if ports is not None:
            pulumi.set(__self__, "ports", ports)
        if service_id is not None:
            pulumi.set(__self__, "service_id", service_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if virtual_machine_id is not None:
            pulumi.set(__self__, "virtual_machine_id", virtual_machine_id)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> pulumi.Input[_builtins.str]:
        """
        Valid values are <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`">`tcp`</span>, <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`">`udp`</span> and <span pulumi-lang-nodejs="`sctp`" pulumi-lang-dotnet="`Sctp`" pulumi-lang-go="`sctp`" pulumi-lang-python="`sctp`" pulumi-lang-yaml="`sctp`" pulumi-lang-java="`sctp`">`sctp`</span>.
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "custom_fields")

    @custom_fields.setter
    def custom_fields(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_fields", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="deviceId")
    def device_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        return pulumi.get(self, "device_id")

    @device_id.setter
    def device_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "device_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def port(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter
    def ports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        """
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "ports", value)

    @_builtins.property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "service_id")

    @service_id.setter
    def service_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="virtualMachineId")
    def virtual_machine_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        return pulumi.get(self, "virtual_machine_id")

    @virtual_machine_id.setter
    def virtual_machine_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "virtual_machine_id", value)


@pulumi.input_type
class _ServiceState:
    def __init__(__self__, *,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 device_id: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.float]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 service_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 virtual_machine_id: Optional[pulumi.Input[_builtins.float]] = None):
        """
        Input properties used for looking up and filtering Service resources.
        :param pulumi.Input[_builtins.float] device_id: Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        :param pulumi.Input[_builtins.float] port: Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] ports: Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        :param pulumi.Input[_builtins.str] protocol: Valid values are <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`">`tcp`</span>, <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`">`udp`</span> and <span pulumi-lang-nodejs="`sctp`" pulumi-lang-dotnet="`Sctp`" pulumi-lang-go="`sctp`" pulumi-lang-python="`sctp`" pulumi-lang-yaml="`sctp`" pulumi-lang-java="`sctp`">`sctp`</span>.
        :param pulumi.Input[_builtins.float] virtual_machine_id: Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        if custom_fields is not None:
            pulumi.set(__self__, "custom_fields", custom_fields)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if device_id is not None:
            pulumi.set(__self__, "device_id", device_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if port is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""port is deprecated: Deprecated""")
        if port is not None:
            pulumi.set(__self__, "port", port)
        if ports is not None:
            pulumi.set(__self__, "ports", ports)
        if protocol is not None:
            pulumi.set(__self__, "protocol", protocol)
        if service_id is not None:
            pulumi.set(__self__, "service_id", service_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tags_alls is not None:
            pulumi.set(__self__, "tags_alls", tags_alls)
        if virtual_machine_id is not None:
            pulumi.set(__self__, "virtual_machine_id", virtual_machine_id)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "custom_fields")

    @custom_fields.setter
    def custom_fields(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_fields", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="deviceId")
    def device_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        return pulumi.get(self, "device_id")

    @device_id.setter
    def device_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "device_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def port(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter
    def ports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        """
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "ports", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`">`tcp`</span>, <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`">`udp`</span> and <span pulumi-lang-nodejs="`sctp`" pulumi-lang-dotnet="`Sctp`" pulumi-lang-go="`sctp`" pulumi-lang-python="`sctp`" pulumi-lang-yaml="`sctp`" pulumi-lang-java="`sctp`">`sctp`</span>.
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "service_id")

    @service_id.setter
    def service_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags_alls")

    @tags_alls.setter
    def tags_alls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags_alls", value)

    @_builtins.property
    @pulumi.getter(name="virtualMachineId")
    def virtual_machine_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        return pulumi.get(self, "virtual_machine_id")

    @virtual_machine_id.setter
    def virtual_machine_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "virtual_machine_id", value)


@pulumi.type_token("netbox:index/service:Service")
class Service(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 device_id: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.float]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 service_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 virtual_machine_id: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        """
        Create a Service resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] device_id: Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        :param pulumi.Input[_builtins.float] port: Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] ports: Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        :param pulumi.Input[_builtins.str] protocol: Valid values are <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`">`tcp`</span>, <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`">`udp`</span> and <span pulumi-lang-nodejs="`sctp`" pulumi-lang-dotnet="`Sctp`" pulumi-lang-go="`sctp`" pulumi-lang-python="`sctp`" pulumi-lang-yaml="`sctp`" pulumi-lang-java="`sctp`">`sctp`</span>.
        :param pulumi.Input[_builtins.float] virtual_machine_id: Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServiceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Service resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ServiceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 device_id: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.float]] = None,
                 ports: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 service_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 virtual_machine_id: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceArgs.__new__(ServiceArgs)

            __props__.__dict__["custom_fields"] = custom_fields
            __props__.__dict__["description"] = description
            __props__.__dict__["device_id"] = device_id
            __props__.__dict__["name"] = name
            __props__.__dict__["port"] = port
            __props__.__dict__["ports"] = ports
            if protocol is None and not opts.urn:
                raise TypeError("Missing required property 'protocol'")
            __props__.__dict__["protocol"] = protocol
            __props__.__dict__["service_id"] = service_id
            __props__.__dict__["tags"] = tags
            __props__.__dict__["virtual_machine_id"] = virtual_machine_id
            __props__.__dict__["tags_alls"] = None
        super(Service, __self__).__init__(
            'netbox:index/service:Service',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            device_id: Optional[pulumi.Input[_builtins.float]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            port: Optional[pulumi.Input[_builtins.float]] = None,
            ports: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
            protocol: Optional[pulumi.Input[_builtins.str]] = None,
            service_id: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            virtual_machine_id: Optional[pulumi.Input[_builtins.float]] = None) -> 'Service':
        """
        Get an existing Service resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] device_id: Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        :param pulumi.Input[_builtins.float] port: Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.float]]] ports: Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        :param pulumi.Input[_builtins.str] protocol: Valid values are <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`">`tcp`</span>, <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`">`udp`</span> and <span pulumi-lang-nodejs="`sctp`" pulumi-lang-dotnet="`Sctp`" pulumi-lang-go="`sctp`" pulumi-lang-python="`sctp`" pulumi-lang-yaml="`sctp`" pulumi-lang-java="`sctp`">`sctp`</span>.
        :param pulumi.Input[_builtins.float] virtual_machine_id: Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ServiceState.__new__(_ServiceState)

        __props__.__dict__["custom_fields"] = custom_fields
        __props__.__dict__["description"] = description
        __props__.__dict__["device_id"] = device_id
        __props__.__dict__["name"] = name
        __props__.__dict__["port"] = port
        __props__.__dict__["ports"] = ports
        __props__.__dict__["protocol"] = protocol
        __props__.__dict__["service_id"] = service_id
        __props__.__dict__["tags"] = tags
        __props__.__dict__["tags_alls"] = tags_alls
        __props__.__dict__["virtual_machine_id"] = virtual_machine_id
        return Service(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "custom_fields")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="deviceId")
    def device_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        return pulumi.get(self, "device_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def port(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        """
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter
    def ports(self) -> pulumi.Output[Optional[Sequence[_builtins.float]]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`">`port`</span> or <span pulumi-lang-nodejs="`ports`" pulumi-lang-dotnet="`Ports`" pulumi-lang-go="`ports`" pulumi-lang-python="`ports`" pulumi-lang-yaml="`ports`" pulumi-lang-java="`ports`">`ports`</span> must be given.
        """
        return pulumi.get(self, "ports")

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> pulumi.Output[_builtins.str]:
        """
        Valid values are <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`">`tcp`</span>, <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`">`udp`</span> and <span pulumi-lang-nodejs="`sctp`" pulumi-lang-dotnet="`Sctp`" pulumi-lang-go="`sctp`" pulumi-lang-python="`sctp`" pulumi-lang-yaml="`sctp`" pulumi-lang-java="`sctp`">`sctp`</span>.
        """
        return pulumi.get(self, "protocol")

    @_builtins.property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "service_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "tags_alls")

    @_builtins.property
    @pulumi.getter(name="virtualMachineId")
    def virtual_machine_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Exactly one of <span pulumi-lang-nodejs="`virtualMachineId`" pulumi-lang-dotnet="`VirtualMachineId`" pulumi-lang-go="`virtualMachineId`" pulumi-lang-python="`virtual_machine_id`" pulumi-lang-yaml="`virtualMachineId`" pulumi-lang-java="`virtualMachineId`">`virtual_machine_id`</span> or <span pulumi-lang-nodejs="`deviceId`" pulumi-lang-dotnet="`DeviceId`" pulumi-lang-go="`deviceId`" pulumi-lang-python="`device_id`" pulumi-lang-yaml="`deviceId`" pulumi-lang-java="`deviceId`">`device_id`</span> must be given.
        """
        return pulumi.get(self, "virtual_machine_id")

