# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SiteArgs', 'Site']

@pulumi.input_type
class SiteArgs:
    def __init__(__self__, *,
                 asn_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 facility: Optional[pulumi.Input[_builtins.str]] = None,
                 group_id: Optional[pulumi.Input[_builtins.float]] = None,
                 latitude: Optional[pulumi.Input[_builtins.float]] = None,
                 longitude: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 physical_address: Optional[pulumi.Input[_builtins.str]] = None,
                 region_id: Optional[pulumi.Input[_builtins.float]] = None,
                 shipping_address: Optional[pulumi.Input[_builtins.str]] = None,
                 site_id: Optional[pulumi.Input[_builtins.str]] = None,
                 slug: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 timezone: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Site resource.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staging`" pulumi-lang-dotnet="`Staging`" pulumi-lang-go="`staging`" pulumi-lang-python="`staging`" pulumi-lang-yaml="`staging`" pulumi-lang-java="`staging`">`staging`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span> and <span pulumi-lang-nodejs="`retired`" pulumi-lang-dotnet="`Retired`" pulumi-lang-go="`retired`" pulumi-lang-python="`retired`" pulumi-lang-yaml="`retired`" pulumi-lang-java="`retired`">`retired`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        if asn_ids is not None:
            pulumi.set(__self__, "asn_ids", asn_ids)
        if comments is not None:
            pulumi.set(__self__, "comments", comments)
        if custom_fields is not None:
            pulumi.set(__self__, "custom_fields", custom_fields)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if facility is not None:
            pulumi.set(__self__, "facility", facility)
        if group_id is not None:
            pulumi.set(__self__, "group_id", group_id)
        if latitude is not None:
            pulumi.set(__self__, "latitude", latitude)
        if longitude is not None:
            pulumi.set(__self__, "longitude", longitude)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if physical_address is not None:
            pulumi.set(__self__, "physical_address", physical_address)
        if region_id is not None:
            pulumi.set(__self__, "region_id", region_id)
        if shipping_address is not None:
            pulumi.set(__self__, "shipping_address", shipping_address)
        if site_id is not None:
            pulumi.set(__self__, "site_id", site_id)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)

    @_builtins.property
    @pulumi.getter(name="asnIds")
    def asn_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        return pulumi.get(self, "asn_ids")

    @asn_ids.setter
    def asn_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "asn_ids", value)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "comments")

    @comments.setter
    def comments(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "comments", value)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "custom_fields")

    @custom_fields.setter
    def custom_fields(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_fields", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def facility(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "facility")

    @facility.setter
    def facility(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "facility", value)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "group_id")

    @group_id.setter
    def group_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "group_id", value)

    @_builtins.property
    @pulumi.getter
    def latitude(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "latitude")

    @latitude.setter
    def latitude(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "latitude", value)

    @_builtins.property
    @pulumi.getter
    def longitude(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "longitude")

    @longitude.setter
    def longitude(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "longitude", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="physicalAddress")
    def physical_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "physical_address")

    @physical_address.setter
    def physical_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "physical_address", value)

    @_builtins.property
    @pulumi.getter(name="regionId")
    def region_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "region_id")

    @region_id.setter
    def region_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "region_id", value)

    @_builtins.property
    @pulumi.getter(name="shippingAddress")
    def shipping_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "shipping_address")

    @shipping_address.setter
    def shipping_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "shipping_address", value)

    @_builtins.property
    @pulumi.getter(name="siteId")
    def site_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "site_id")

    @site_id.setter
    def site_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "site_id", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staging`" pulumi-lang-dotnet="`Staging`" pulumi-lang-go="`staging`" pulumi-lang-python="`staging`" pulumi-lang-yaml="`staging`" pulumi-lang-java="`staging`">`staging`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span> and <span pulumi-lang-nodejs="`retired`" pulumi-lang-dotnet="`Retired`" pulumi-lang-go="`retired`" pulumi-lang-python="`retired`" pulumi-lang-yaml="`retired`" pulumi-lang-java="`retired`">`retired`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "timezone", value)


@pulumi.input_type
class _SiteState:
    def __init__(__self__, *,
                 asn_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 facility: Optional[pulumi.Input[_builtins.str]] = None,
                 group_id: Optional[pulumi.Input[_builtins.float]] = None,
                 latitude: Optional[pulumi.Input[_builtins.float]] = None,
                 longitude: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 physical_address: Optional[pulumi.Input[_builtins.str]] = None,
                 region_id: Optional[pulumi.Input[_builtins.float]] = None,
                 shipping_address: Optional[pulumi.Input[_builtins.str]] = None,
                 site_id: Optional[pulumi.Input[_builtins.str]] = None,
                 slug: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 timezone: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Site resources.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staging`" pulumi-lang-dotnet="`Staging`" pulumi-lang-go="`staging`" pulumi-lang-python="`staging`" pulumi-lang-yaml="`staging`" pulumi-lang-java="`staging`">`staging`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span> and <span pulumi-lang-nodejs="`retired`" pulumi-lang-dotnet="`Retired`" pulumi-lang-go="`retired`" pulumi-lang-python="`retired`" pulumi-lang-yaml="`retired`" pulumi-lang-java="`retired`">`retired`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        if asn_ids is not None:
            pulumi.set(__self__, "asn_ids", asn_ids)
        if comments is not None:
            pulumi.set(__self__, "comments", comments)
        if custom_fields is not None:
            pulumi.set(__self__, "custom_fields", custom_fields)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if facility is not None:
            pulumi.set(__self__, "facility", facility)
        if group_id is not None:
            pulumi.set(__self__, "group_id", group_id)
        if latitude is not None:
            pulumi.set(__self__, "latitude", latitude)
        if longitude is not None:
            pulumi.set(__self__, "longitude", longitude)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if physical_address is not None:
            pulumi.set(__self__, "physical_address", physical_address)
        if region_id is not None:
            pulumi.set(__self__, "region_id", region_id)
        if shipping_address is not None:
            pulumi.set(__self__, "shipping_address", shipping_address)
        if site_id is not None:
            pulumi.set(__self__, "site_id", site_id)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tags_alls is not None:
            pulumi.set(__self__, "tags_alls", tags_alls)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)

    @_builtins.property
    @pulumi.getter(name="asnIds")
    def asn_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]:
        return pulumi.get(self, "asn_ids")

    @asn_ids.setter
    def asn_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]]):
        pulumi.set(self, "asn_ids", value)

    @_builtins.property
    @pulumi.getter
    def comments(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "comments")

    @comments.setter
    def comments(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "comments", value)

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "custom_fields")

    @custom_fields.setter
    def custom_fields(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "custom_fields", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def facility(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "facility")

    @facility.setter
    def facility(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "facility", value)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "group_id")

    @group_id.setter
    def group_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "group_id", value)

    @_builtins.property
    @pulumi.getter
    def latitude(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "latitude")

    @latitude.setter
    def latitude(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "latitude", value)

    @_builtins.property
    @pulumi.getter
    def longitude(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "longitude")

    @longitude.setter
    def longitude(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "longitude", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="physicalAddress")
    def physical_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "physical_address")

    @physical_address.setter
    def physical_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "physical_address", value)

    @_builtins.property
    @pulumi.getter(name="regionId")
    def region_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "region_id")

    @region_id.setter
    def region_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "region_id", value)

    @_builtins.property
    @pulumi.getter(name="shippingAddress")
    def shipping_address(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "shipping_address")

    @shipping_address.setter
    def shipping_address(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "shipping_address", value)

    @_builtins.property
    @pulumi.getter(name="siteId")
    def site_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "site_id")

    @site_id.setter
    def site_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "site_id", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staging`" pulumi-lang-dotnet="`Staging`" pulumi-lang-go="`staging`" pulumi-lang-python="`staging`" pulumi-lang-yaml="`staging`" pulumi-lang-java="`staging`">`staging`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span> and <span pulumi-lang-nodejs="`retired`" pulumi-lang-dotnet="`Retired`" pulumi-lang-go="`retired`" pulumi-lang-python="`retired`" pulumi-lang-yaml="`retired`" pulumi-lang-java="`retired`">`retired`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags_alls")

    @tags_alls.setter
    def tags_alls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags_alls", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "timezone", value)


@pulumi.type_token("netbox:index/site:Site")
class Site(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 asn_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 facility: Optional[pulumi.Input[_builtins.str]] = None,
                 group_id: Optional[pulumi.Input[_builtins.float]] = None,
                 latitude: Optional[pulumi.Input[_builtins.float]] = None,
                 longitude: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 physical_address: Optional[pulumi.Input[_builtins.str]] = None,
                 region_id: Optional[pulumi.Input[_builtins.float]] = None,
                 shipping_address: Optional[pulumi.Input[_builtins.str]] = None,
                 site_id: Optional[pulumi.Input[_builtins.str]] = None,
                 slug: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 timezone: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Site resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staging`" pulumi-lang-dotnet="`Staging`" pulumi-lang-go="`staging`" pulumi-lang-python="`staging`" pulumi-lang-yaml="`staging`" pulumi-lang-java="`staging`">`staging`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span> and <span pulumi-lang-nodejs="`retired`" pulumi-lang-dotnet="`Retired`" pulumi-lang-go="`retired`" pulumi-lang-python="`retired`" pulumi-lang-yaml="`retired`" pulumi-lang-java="`retired`">`retired`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SiteArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Site resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param SiteArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SiteArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 asn_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
                 comments: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 facility: Optional[pulumi.Input[_builtins.str]] = None,
                 group_id: Optional[pulumi.Input[_builtins.float]] = None,
                 latitude: Optional[pulumi.Input[_builtins.float]] = None,
                 longitude: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 physical_address: Optional[pulumi.Input[_builtins.str]] = None,
                 region_id: Optional[pulumi.Input[_builtins.float]] = None,
                 shipping_address: Optional[pulumi.Input[_builtins.str]] = None,
                 site_id: Optional[pulumi.Input[_builtins.str]] = None,
                 slug: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 timezone: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SiteArgs.__new__(SiteArgs)

            __props__.__dict__["asn_ids"] = asn_ids
            __props__.__dict__["comments"] = comments
            __props__.__dict__["custom_fields"] = custom_fields
            __props__.__dict__["description"] = description
            __props__.__dict__["facility"] = facility
            __props__.__dict__["group_id"] = group_id
            __props__.__dict__["latitude"] = latitude
            __props__.__dict__["longitude"] = longitude
            __props__.__dict__["name"] = name
            __props__.__dict__["physical_address"] = physical_address
            __props__.__dict__["region_id"] = region_id
            __props__.__dict__["shipping_address"] = shipping_address
            __props__.__dict__["site_id"] = site_id
            __props__.__dict__["slug"] = slug
            __props__.__dict__["status"] = status
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_id"] = tenant_id
            __props__.__dict__["timezone"] = timezone
            __props__.__dict__["tags_alls"] = None
        super(Site, __self__).__init__(
            'netbox:index/site:Site',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            asn_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.float]]]] = None,
            comments: Optional[pulumi.Input[_builtins.str]] = None,
            custom_fields: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            facility: Optional[pulumi.Input[_builtins.str]] = None,
            group_id: Optional[pulumi.Input[_builtins.float]] = None,
            latitude: Optional[pulumi.Input[_builtins.float]] = None,
            longitude: Optional[pulumi.Input[_builtins.float]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            physical_address: Optional[pulumi.Input[_builtins.str]] = None,
            region_id: Optional[pulumi.Input[_builtins.float]] = None,
            shipping_address: Optional[pulumi.Input[_builtins.str]] = None,
            site_id: Optional[pulumi.Input[_builtins.str]] = None,
            slug: Optional[pulumi.Input[_builtins.str]] = None,
            status: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
            timezone: Optional[pulumi.Input[_builtins.str]] = None) -> 'Site':
        """
        Get an existing Site resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staging`" pulumi-lang-dotnet="`Staging`" pulumi-lang-go="`staging`" pulumi-lang-python="`staging`" pulumi-lang-yaml="`staging`" pulumi-lang-java="`staging`">`staging`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span> and <span pulumi-lang-nodejs="`retired`" pulumi-lang-dotnet="`Retired`" pulumi-lang-go="`retired`" pulumi-lang-python="`retired`" pulumi-lang-yaml="`retired`" pulumi-lang-java="`retired`">`retired`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SiteState.__new__(_SiteState)

        __props__.__dict__["asn_ids"] = asn_ids
        __props__.__dict__["comments"] = comments
        __props__.__dict__["custom_fields"] = custom_fields
        __props__.__dict__["description"] = description
        __props__.__dict__["facility"] = facility
        __props__.__dict__["group_id"] = group_id
        __props__.__dict__["latitude"] = latitude
        __props__.__dict__["longitude"] = longitude
        __props__.__dict__["name"] = name
        __props__.__dict__["physical_address"] = physical_address
        __props__.__dict__["region_id"] = region_id
        __props__.__dict__["shipping_address"] = shipping_address
        __props__.__dict__["site_id"] = site_id
        __props__.__dict__["slug"] = slug
        __props__.__dict__["status"] = status
        __props__.__dict__["tags"] = tags
        __props__.__dict__["tags_alls"] = tags_alls
        __props__.__dict__["tenant_id"] = tenant_id
        __props__.__dict__["timezone"] = timezone
        return Site(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="asnIds")
    def asn_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.float]]]:
        return pulumi.get(self, "asn_ids")

    @_builtins.property
    @pulumi.getter
    def comments(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "comments")

    @_builtins.property
    @pulumi.getter(name="customFields")
    def custom_fields(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "custom_fields")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def facility(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "facility")

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "group_id")

    @_builtins.property
    @pulumi.getter
    def latitude(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "latitude")

    @_builtins.property
    @pulumi.getter
    def longitude(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "longitude")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="physicalAddress")
    def physical_address(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "physical_address")

    @_builtins.property
    @pulumi.getter(name="regionId")
    def region_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "region_id")

    @_builtins.property
    @pulumi.getter(name="shippingAddress")
    def shipping_address(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "shipping_address")

    @_builtins.property
    @pulumi.getter(name="siteId")
    def site_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "site_id")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`staging`" pulumi-lang-dotnet="`Staging`" pulumi-lang-go="`staging`" pulumi-lang-python="`staging`" pulumi-lang-yaml="`staging`" pulumi-lang-java="`staging`">`staging`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>, <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`">`decommissioning`</span> and <span pulumi-lang-nodejs="`retired`" pulumi-lang-dotnet="`Retired`" pulumi-lang-go="`retired`" pulumi-lang-python="`retired`" pulumi-lang-yaml="`retired`" pulumi-lang-java="`retired`">`retired`</span>. Defaults to <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span>.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "tags_alls")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "timezone")

