# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['VpnTunnelArgs', 'VpnTunnel']

@pulumi.input_type
class VpnTunnelArgs:
    def __init__(__self__, *,
                 encapsulation: pulumi.Input[_builtins.str],
                 status: pulumi.Input[_builtins.str],
                 tunnel_group_id: pulumi.Input[_builtins.float],
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 tunnel_id: Optional[pulumi.Input[_builtins.float]] = None,
                 vpn_tunnel_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a VpnTunnel resource.
        :param pulumi.Input[_builtins.str] encapsulation: Valid values are `ipsec-transport`, `ipsec-tunnel`, `ip-ip` and <span pulumi-lang-nodejs="`gre`" pulumi-lang-dotnet="`Gre`" pulumi-lang-go="`gre`" pulumi-lang-python="`gre`" pulumi-lang-yaml="`gre`" pulumi-lang-java="`gre`">`gre`</span>.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span> and <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>.
        """
        pulumi.set(__self__, "encapsulation", encapsulation)
        pulumi.set(__self__, "status", status)
        pulumi.set(__self__, "tunnel_group_id", tunnel_group_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if tunnel_id is not None:
            pulumi.set(__self__, "tunnel_id", tunnel_id)
        if vpn_tunnel_id is not None:
            pulumi.set(__self__, "vpn_tunnel_id", vpn_tunnel_id)

    @_builtins.property
    @pulumi.getter
    def encapsulation(self) -> pulumi.Input[_builtins.str]:
        """
        Valid values are `ipsec-transport`, `ipsec-tunnel`, `ip-ip` and <span pulumi-lang-nodejs="`gre`" pulumi-lang-dotnet="`Gre`" pulumi-lang-go="`gre`" pulumi-lang-python="`gre`" pulumi-lang-yaml="`gre`" pulumi-lang-java="`gre`">`gre`</span>.
        """
        return pulumi.get(self, "encapsulation")

    @encapsulation.setter
    def encapsulation(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "encapsulation", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[_builtins.str]:
        """
        Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span> and <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="tunnelGroupId")
    def tunnel_group_id(self) -> pulumi.Input[_builtins.float]:
        return pulumi.get(self, "tunnel_group_id")

    @tunnel_group_id.setter
    def tunnel_group_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "tunnel_group_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter(name="tunnelId")
    def tunnel_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tunnel_id")

    @tunnel_id.setter
    def tunnel_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tunnel_id", value)

    @_builtins.property
    @pulumi.getter(name="vpnTunnelId")
    def vpn_tunnel_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "vpn_tunnel_id")

    @vpn_tunnel_id.setter
    def vpn_tunnel_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vpn_tunnel_id", value)


@pulumi.input_type
class _VpnTunnelState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 encapsulation: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 tunnel_group_id: Optional[pulumi.Input[_builtins.float]] = None,
                 tunnel_id: Optional[pulumi.Input[_builtins.float]] = None,
                 vpn_tunnel_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering VpnTunnel resources.
        :param pulumi.Input[_builtins.str] encapsulation: Valid values are `ipsec-transport`, `ipsec-tunnel`, `ip-ip` and <span pulumi-lang-nodejs="`gre`" pulumi-lang-dotnet="`Gre`" pulumi-lang-go="`gre`" pulumi-lang-python="`gre`" pulumi-lang-yaml="`gre`" pulumi-lang-java="`gre`">`gre`</span>.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span> and <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if encapsulation is not None:
            pulumi.set(__self__, "encapsulation", encapsulation)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tags_alls is not None:
            pulumi.set(__self__, "tags_alls", tags_alls)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if tunnel_group_id is not None:
            pulumi.set(__self__, "tunnel_group_id", tunnel_group_id)
        if tunnel_id is not None:
            pulumi.set(__self__, "tunnel_id", tunnel_id)
        if vpn_tunnel_id is not None:
            pulumi.set(__self__, "vpn_tunnel_id", vpn_tunnel_id)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def encapsulation(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are `ipsec-transport`, `ipsec-tunnel`, `ip-ip` and <span pulumi-lang-nodejs="`gre`" pulumi-lang-dotnet="`Gre`" pulumi-lang-go="`gre`" pulumi-lang-python="`gre`" pulumi-lang-yaml="`gre`" pulumi-lang-java="`gre`">`gre`</span>.
        """
        return pulumi.get(self, "encapsulation")

    @encapsulation.setter
    def encapsulation(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "encapsulation", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span> and <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags_alls")

    @tags_alls.setter
    def tags_alls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags_alls", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter(name="tunnelGroupId")
    def tunnel_group_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tunnel_group_id")

    @tunnel_group_id.setter
    def tunnel_group_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tunnel_group_id", value)

    @_builtins.property
    @pulumi.getter(name="tunnelId")
    def tunnel_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "tunnel_id")

    @tunnel_id.setter
    def tunnel_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tunnel_id", value)

    @_builtins.property
    @pulumi.getter(name="vpnTunnelId")
    def vpn_tunnel_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "vpn_tunnel_id")

    @vpn_tunnel_id.setter
    def vpn_tunnel_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vpn_tunnel_id", value)


@pulumi.type_token("netbox:index/vpnTunnel:VpnTunnel")
class VpnTunnel(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 encapsulation: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 tunnel_group_id: Optional[pulumi.Input[_builtins.float]] = None,
                 tunnel_id: Optional[pulumi.Input[_builtins.float]] = None,
                 vpn_tunnel_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a VpnTunnel resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] encapsulation: Valid values are `ipsec-transport`, `ipsec-tunnel`, `ip-ip` and <span pulumi-lang-nodejs="`gre`" pulumi-lang-dotnet="`Gre`" pulumi-lang-go="`gre`" pulumi-lang-python="`gre`" pulumi-lang-yaml="`gre`" pulumi-lang-java="`gre`">`gre`</span>.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span> and <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VpnTunnelArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a VpnTunnel resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param VpnTunnelArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VpnTunnelArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 encapsulation: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
                 tunnel_group_id: Optional[pulumi.Input[_builtins.float]] = None,
                 tunnel_id: Optional[pulumi.Input[_builtins.float]] = None,
                 vpn_tunnel_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VpnTunnelArgs.__new__(VpnTunnelArgs)

            __props__.__dict__["description"] = description
            if encapsulation is None and not opts.urn:
                raise TypeError("Missing required property 'encapsulation'")
            __props__.__dict__["encapsulation"] = encapsulation
            __props__.__dict__["name"] = name
            if status is None and not opts.urn:
                raise TypeError("Missing required property 'status'")
            __props__.__dict__["status"] = status
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_id"] = tenant_id
            if tunnel_group_id is None and not opts.urn:
                raise TypeError("Missing required property 'tunnel_group_id'")
            __props__.__dict__["tunnel_group_id"] = tunnel_group_id
            __props__.__dict__["tunnel_id"] = tunnel_id
            __props__.__dict__["vpn_tunnel_id"] = vpn_tunnel_id
            __props__.__dict__["tags_alls"] = None
        super(VpnTunnel, __self__).__init__(
            'netbox:index/vpnTunnel:VpnTunnel',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            encapsulation: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            status: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tags_alls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            tenant_id: Optional[pulumi.Input[_builtins.float]] = None,
            tunnel_group_id: Optional[pulumi.Input[_builtins.float]] = None,
            tunnel_id: Optional[pulumi.Input[_builtins.float]] = None,
            vpn_tunnel_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'VpnTunnel':
        """
        Get an existing VpnTunnel resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] encapsulation: Valid values are `ipsec-transport`, `ipsec-tunnel`, `ip-ip` and <span pulumi-lang-nodejs="`gre`" pulumi-lang-dotnet="`Gre`" pulumi-lang-go="`gre`" pulumi-lang-python="`gre`" pulumi-lang-yaml="`gre`" pulumi-lang-java="`gre`">`gre`</span>.
        :param pulumi.Input[_builtins.str] status: Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span> and <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _VpnTunnelState.__new__(_VpnTunnelState)

        __props__.__dict__["description"] = description
        __props__.__dict__["encapsulation"] = encapsulation
        __props__.__dict__["name"] = name
        __props__.__dict__["status"] = status
        __props__.__dict__["tags"] = tags
        __props__.__dict__["tags_alls"] = tags_alls
        __props__.__dict__["tenant_id"] = tenant_id
        __props__.__dict__["tunnel_group_id"] = tunnel_group_id
        __props__.__dict__["tunnel_id"] = tunnel_id
        __props__.__dict__["vpn_tunnel_id"] = vpn_tunnel_id
        return VpnTunnel(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def encapsulation(self) -> pulumi.Output[_builtins.str]:
        """
        Valid values are `ipsec-transport`, `ipsec-tunnel`, `ip-ip` and <span pulumi-lang-nodejs="`gre`" pulumi-lang-dotnet="`Gre`" pulumi-lang-go="`gre`" pulumi-lang-python="`gre`" pulumi-lang-yaml="`gre`" pulumi-lang-java="`gre`">`gre`</span>.
        """
        return pulumi.get(self, "encapsulation")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Valid values are <span pulumi-lang-nodejs="`planned`" pulumi-lang-dotnet="`Planned`" pulumi-lang-go="`planned`" pulumi-lang-python="`planned`" pulumi-lang-yaml="`planned`" pulumi-lang-java="`planned`">`planned`</span>, <span pulumi-lang-nodejs="`active`" pulumi-lang-dotnet="`Active`" pulumi-lang-go="`active`" pulumi-lang-python="`active`" pulumi-lang-yaml="`active`" pulumi-lang-java="`active`">`active`</span> and <span pulumi-lang-nodejs="`disabled`" pulumi-lang-dotnet="`Disabled`" pulumi-lang-go="`disabled`" pulumi-lang-python="`disabled`" pulumi-lang-yaml="`disabled`" pulumi-lang-java="`disabled`">`disabled`</span>.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tagsAlls")
    def tags_alls(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "tags_alls")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter(name="tunnelGroupId")
    def tunnel_group_id(self) -> pulumi.Output[_builtins.float]:
        return pulumi.get(self, "tunnel_group_id")

    @_builtins.property
    @pulumi.getter(name="tunnelId")
    def tunnel_id(self) -> pulumi.Output[Optional[_builtins.float]]:
        return pulumi.get(self, "tunnel_id")

    @_builtins.property
    @pulumi.getter(name="vpnTunnelId")
    def vpn_tunnel_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "vpn_tunnel_id")

